### ISSUE TITLE
Other Android based system compatibility

### ISSUE THREAD

**Issue by Tierney0115** [openstf/stf#121]
Hi, I have tried other Android based mobile systems like EMUI 3.0 and MIUI 6, but failed to connect. Have you considered support other Android based systems before? Could you please give me some hints about how to support them? Thanks.

**Comment by sorccu** [comment]
In general all Android-based systems like MIUI, Amazon's Fire OS, CyanogenMod etc. are fully supported (with the exception of Firefox OS). However, because we use private APIs behind the scenes, some individual models don't work. I don't have an EMUI device to test with right now so I can't say anything about that, but I know that all versions of MIUI work fine. For example, I have a Redmi Note 2, Meizu M2 Note, and a ZTE V5 PRO right here, and they all work just fine.

However, I believe Redmi Hongmi is one of the phones that does not work right now, so if that's the one you tried, perhaps try something else instead.

Also, by "failing to connect" I assume you are getting some kind of errors in the logs. Could you perhaps post the logs here? Feel free to remove any identifying information first, though.

**Comment by Tierney0115** [comment]
Hi, thank you for your reply. I have figured it out that on my EMUI device, I need to accept a service manually on my phone and it worked. But I don't have to do it on my Galaxy.  Maybe it caused by the EMUI security configuration. Anyway, thanks.
