### ISSUE TITLE
Privilege field in LDAP

### ISSUE THREAD

**Issue by FRodero** [openstf/stf#1226]
Hi,

I have just updated STF in our machine. We use LDAP for authentication and I have seen a new parameter called 'Privilege'.

![image](https://user-images.githubusercontent.com/17677248/81293055-f933a300-906c-11ea-843b-fdb4dcc903da.png)

How could I select that field in LDAP? We have an issue because all users using role 'user' and can't modify any device, group and so on.

Thanks!

**Comment by denis99999** [comment]
@FRodero ,

This `privilege` field of users' table is not related to LDAP, it is used to distinguish the administrator user from other users.

A simple user with a `user privilege` is able to create transient groups (i.e. reservation of a set of devices for a set of users) but **he is not authorized** to manage devices and users (i.e. add/remove objects in database) as well as to create origin groups (i.e. partition of devices with a standard or bookable class), only the administrator user with the `admin privilege` can do that, please report to [GroupFeature.pdf](https://github.com/openstf/stf/blob/master/doc/GroupFeature.pdf) documentation for a detailed explanation of the group feature and how to use it.

**Comment by FRodero** [comment]
@denis99999 thanks for your answer.

My issue is with that "admin privilege". The creation group just was an example. I need assign "admin role" to another user from LDAP. I need to indicate that option in somewhere in STF. When I sign in STF with my user I will need to be "admin user" also. That problem exist because Administrator exist in mock auth not in ldap auth.

Perhaps I explained wrongly. Thank you in advance.

**Comment by denis99999** [comment]
@FRodero ,

You can't assign `admin` privilege to more than one user, and before to install or update your STF platform you can specify the name and the email of the administrator user only if the corresponding built-in object does not already exist, default values are `administrator` and `administrator@fakedomain.com`, report to `Running` section of `README.md` for detailed explanations.

Now I understand you STF platform is updated, it is too late to change these properties -- except if you made a backup of your previous rethinkdb database --, so in short you have to create a LDAP entry for the administrator user if it does not already exist using the default values, otherwise you have to rebuild your database specifying the right credentials for the administrator user.

**Comment by FRodero** [comment]
Thanks a lot @denis99999.

I have already an admin user in my STF platform.
