### ISSUE TITLE
How can i access STF with my own user auth system?

### ISSUE THREAD

**Issue by LiufxLucky365** [openstf/stf#132]
Dear all

I have my own user database, how can i access STF with my own information ?

**Comment by sorccu** [comment]
Authentication is provided by small, separate web apps. Use one of the units in https://github.com/openstf/stf/tree/master/lib/units/auth as an example and make your own. And since they're separate apps, as long as yours does the same thing (forwards to STF with a signed JWT token in query parameters), it doesn't even need to be written in JS. Use the source code as your guide.

**Comment by LiufxLucky365** [comment]
can you describe detail ?

i cannot understand the nodejs code logic.

my server language is PHP, how can i realize what you say ?

thanks

**Comment by LiufxLucky365** [comment]
ok, I really get what you mean, i use JWT realize what i want, thank you all the same!
