### ISSUE TITLE
Some problem about option '--adb-host'

### ISSUE THREAD

**Issue by LiufxLucky365** [openstf/stf#155]
my adb server and STF is in different host, can i use this option to set the adb server ? 

```shell
stf local -R  --adb-host 172.18.146.123 
```

and on my 172.18.146.123 host, i run
```shell
adb kill-server && adb start-server
```

but STF report
```shell
Unhandled rejection Error: connect ECONNREFUSED 172.18.146.123:5037
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

anybody who knows where am i wrong ? Thanks

**Comment by vbanthia** [comment]
This is because stf is not able to connect adb host server. By default adb server listen only on localhost. In order to make it a remote host you must have to make it listen on all network interfaces.

Start adb server with below command

``` 
adb kill-server      # Just to make sure
adb -a -P 5037 fork-server server&
```

And restart stf using the same command, `stf local -R  --adb-host 172.18.146.123 `. It should work.

**Comment by sorccu** [comment]
@vbanthia is correct.

Alternatively you can use an SSH tunnel, `socat` or some other way to make the port accessible.

For example you could run this command on the app server where `stf local` is running:

```bash
ssh user@server -L 5037:127.0.0.1:5037
```

.. which makes the remote ADB server available on the same port on the app server. You wouldn't even need to use `--adb-host`. `adb forward` still wouldn't work globally, though. For that, the modified adb command is the simplest solution.
