### ISSUE TITLE
Add RethinkDB server to docker file

### ISSUE THREAD

**Issue by matis11** [openstf/stf#163]
Hello.

I'm trying to run stf locally and I have a problem with connecting to RethinkDB from Docker. Is there any reason why don't you put rethinkdb server startup in dockerfile?

Could you provide any support to help me connect stf to rethinkdb locally on docker containers?

Cheers!

**Comment by sorccu** [comment]
Because that's not how containers are supposed to work (although I'll admit that it is an almost religious issue). There should be only one process (+ possible worker processes) per container. You could argue that we should just put both of them inside the same container and use supervisor or something else to manage them, but I would just reply that you're doing it wrong, i.e. the *Virtual Machine* way, not the *container* way, so don't waste your time.

Also, having the DB and the app on the same server is not a proper, scalable deployment.

The [deployment guide](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) provides some examples. It's a bit heavy, yes, but it's meant to be that way.

**Comment by sorccu** [comment]
#122 might also help if you're not using docker for RethinkDB.
