### ISSUE TITLE
running stf local

### ISSUE THREAD

**Issue by romitincedoinc** [openstf/stf#165]
I have installed docker and pulled the image from the docker hub. 
Now i am confused what to do next?
Do i need to install all the requirements explicitly on my ubuntu machine including rethinkdb ?
I have also tried to ref. to the solution given by you but you have mentioned there to see the deployment file, which makes me confused to understand difference between stf local and actual deployment.

Can you please help me.

**Comment by vbanthia** [comment]
> which makes me confused to understand difference between stf local and actual deployment.

STF is a distributed application which means it is supposed to be run on a cluster of computers in production environment instead of a single machine. stf local feature is developed just for development purpose. You are not supposed to use it in production environment.

In order to deploy STF app in production, you will need
1. A cluster of computers where you can connect your devices
2. A tool which can deploy, stf docker container in the cluster

There are many ways to do this but [STF's Deployment doc](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) suggest, [CoreOS + Fleet combination] (https://coreos.com/). CoreOS is to make cluster and Fleet is run STF services inside cluster.

I highly recommend you to go through all the [CoreOS documentation](https://coreos.com/docs/) even if you don't plan to use CoreOS because that will give you and idea about computer cluster. After you finish reading these docs and if you reread the deployment doc, you will automatically understand everything.


> Do i need to install all the requirements explicitly on my ubuntu machine including rethinkdb ?

No, you do not need to install any thing on your ubuntu machine. All the required dependencies are already installed in docker image. You should consider reading [docker documentation] (https://docs.docker.com/) regarding how docker works.

>  including rethinkdb ?

There are many ways you can create database (rethinkdb) cluster. You can use or not use docker, its totally your choice. https://github.com/openstf/stf/issues/163 might helps.

**Comment by romitincedoinc** [comment]
HI 

Thanks for your reply.

Yes i am reading coreos in the meanwhile i have installed docker on ubuntu 14.04 lts and trying to get the things done.

I have also tried the "Mitesh Shah" method , by that i am able to create the tables in the db but i am getting an error of  stf device. Can you help me in this


FTL/reaper 28116 [reaper001] Unable to load initial state { name: 'ReqlOpFailedError',
  msg: 'Index `present` was not found on table `stf.devices`.',
  frames: [],
  message: 'Index `present` was not found on table `stf.devices` in:\nr.table("devices").getAll(true, {index: "present"})\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' }
FTL/util:lifecycle 28116 [reaper001] Shutting down due to fatal error
FTL/cli:local 28106 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)

**Comment by vbanthia** [comment]
Well, this is a known bug which is already fixed in master branch. Looks like you have installed stf using npm and npm latest version is pretty old compare to master branch.

You have two choices.
* Add 'present' index manually in devices table

  * Go to rethinkdb administrative UI (http://localhost:8080)
  * Open Data Explorer
  * Add index using query 
```js
 r.db("stf").table("devices").indexCreate('present');
 ``` 

* Make sure your device table should look like below

```

* Use master branch

You can find instruction [here](https://github.com/openstf/stf/issues/149#issuecomment-150489725)

**Comment by romitincedoinc** [comment]
Hi
 I am able to up the system and up the ui on 7100 port . Currently it is showing zero devices connected.
To test i started android studio on which i have installed genymotion. When i start avirtual device from genymotion , i suddenly get an error , which says try reconnect. can you please help me in resolving this

FTL/util:lifecycle 4024 [*] Tracker had an error Error: Connection closed
    at /usr/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:22:15
    at tryCatcher (/usr/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/usr/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/catch_filter.js:40:36)
    at CatchFilter.tryCatcher (/usr/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/usr/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
FTL/util:lifecycle 4024 [*] Shutting down due to fatal error
FTL/cli:local 4011 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
INF/cli:local 4011 [*] Shutting down all child processes
INF/util:lifecycle 4015 [app001] Winding down for graceful exit
INF/util:lifecycle 4016 [dev001] Winding down for graceful exit
INF/util:lifecycle 4017 [proc001] Winding down for graceful exit
INF/util:lifecycle 4020 [proc002] Winding down for graceful exit
INF/util:lifecycle 4022 [reaper001] Winding down for graceful exit
WRN/db 4022 [reaper001] Connection closed
INF/db 4022 [reaper001] Connecting to 127.0.0.1:28015
WRN/db 4017 [proc001] Connection closed
INF/db 4017 [proc001] Connecting to 127.0.0.1:28015
INF/util:lifecycle 4026 [*] Winding down for graceful exit
INF/util:lifecycle 4028 [*] Winding down for graceful exit
INF/auth-mock 4026 [*] Waiting for client connections to end
INF/util:lifecycle 4029 [*] Winding down for graceful exit
WRN/db 4020 [proc002] Connection closed
INF/db 4020 [proc002] Connecting to 127.0.0.1:28015
WRN/db 4029 [*] Connection closed
WRN/db 4028 [*] Connection closed
INF/db 4029 [*] Connecting to 127.0.0.1:28015
INF/db 4028 [*] Connecting to 127.0.0.1:28015

**Comment by romitincedoinc** [comment]
Hi,

Thanks the system is up on Ubuntu 14.04 LTS single machine and now I'm exploring it.
But yes the best thing would be to setup the production environment using core os.

**Comment by vbanthia** [comment]
nice!

**Comment by vbanthia** [comment]
@romitincedoinc 

Can you tell, which rethinkdb version you were using?
