### ISSUE TITLE
OSX installation failure - missing documentation

### ISSUE THREAD

**Issue by shouse** [openstf/stf#17]
I had to install pkg-config to get it to work:
$ brew install pkg-config
Perhaps update your documentation.  You can close this as non-issue of course.

**Comment by adrien-aubel** [comment]
+1

**Comment by nasahapps** [comment]
Another OSX installation failure when doing `npm install -g stf` is this:  

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "stf"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1
npm ERR! path /usr/local/lib/node_modules/stf/node_modules/stf-wiki
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! ENOTEMPTY, rmdir '/usr/local/lib/node_modules/stf/node_modules/stf-wiki'
npm ERR!  

npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/stf/node_modules/stf-wiki'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/stf/node_modules/stf-wiki']
npm ERR! error rolling back   errno: -66,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/stf/node_modules/stf-wiki' }

**Comment by sorccu** [comment]
@nasahapps Can I ask how you installed node? Looks to me like you probably used the official installer, but I'm asking just to be sure.

**Comment by nasahapps** [comment]
`brew install node`

**Comment by sorccu** [comment]
@nasahapps It does work for me on latest Yosemite, although brew installed the latest Node.js (0.12.7) instead of 0.12.0. Perhaps try upgrading?

I've seen the same error before due to having my repo inside Dropbox and/or BitTorrent Sync (they presumably "recovered" some of the files NPM wanted to delete before it got do delete the folder), but I don't think that's the case here. 

I've also seen similar errors occur due to permission problems, although the logs usually tell you if that's the case (it's usually a small message before the other errors). Might be worth running `brew doctor` and Disk Utility's Repair Disk Permissions just to be sure, though.

**Comment by shouse** [comment]
Thanks.  And bada$$ software BTW
