### ISSUE TITLE
Can't open settings over STF UI on Samsung Devices

### ISSUE THREAD

**Issue by FelixHahn** [openstf/stf#187]
Hi,

we stumpled over another bug.
We can't access the phone settings over "Dashboard" --> "Apps" --> "Settings" on Samsung devices.

We tested it with a Samsung Galaxy S3 (Android 4.43) and Samsung Galaxy S5 (Android 5.0)

Thank you and take care.

Kind regards

Felix Hahn

**Comment by vbanthia** [comment]
Well, it should work.

Can you check if the below command is launching setting app in your Samsung device.

```
adb -s DEVICE_SERIAL shell am start -a android.intent.action.MAIN -n com.android.settings/.Settings
```

**Comment by FelixHahn** [comment]
Hi,

we tested it again with both Samsungs and getting the following output:

```
* daemon not running. starting it now on port 5038 *
* daemon started successfully *
error: device not found
```
Used following command with the Galaxy S5

`adb -s 19e99847 shell am start -a android.intent.action.MAIN -n com.android.settings/.Settings`

There ist a Screenshot of the "info" task of our Galaxy S5:

![device_serial](https://cloud.githubusercontent.com/assets/9655106/11399802/ec4b7684-9389-11e5-8bdd-e441e9d97607.PNG)

We can access the settings with LG and Sony devices.

Kind regards

Felix Hahn

**Comment by vbanthia** [comment]
Did you run that command in the server machine(where device is connected and stf is running) or some where else?

Since, STF can access the devices `device not found` error is bit weird.

Please do following things
1. Post stf logs when you click setting button
2. Open settings app manually in the device and run following command and post outputs here.

```
adb -s DEVICE_SERIAL shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp'
```
Don't forget to run command in the machine where it is connected.
