### ISSUE TITLE
How can i access STF from other machines( the STF server is working behind a firewall)

### ISSUE THREAD

**Issue by lincoln002** [openstf/stf#252]
The guide "If you want to access STF from other machines, you can add the --public-ip option for quick testing."  But if the STF server is working behind a firewall, maybe the service ports also have been mapped to new ports, so what can do more beside add the --public-ip option?

**Comment by vbanthia** [comment]
well if you are just looking for a work around then I can suggest one.

Generally `80` & `443` ports are open in most of the firewalls. You can use `--poorxy-port` option while running stf server and set port = 80. In order to use `80` port, you need to stf as sudo. Run command will look something like this

```
sudo stf local --public-ip x.x.x.x --poorxy-port 80 
```

There will still be a limitation, you won't be able to use stf's `remote-debug` feature as it needs more open ports `7400 ~ 7700` in case you are running stf as `stf local`.

**Comment by lincoln002** [comment]
vbanthia,First Thanks.

then, i have to say sorry.  i have not describe my problems clearly. Actually, my network environment as follow:
                        proxy machine(with public ip machine)            STF Server machine(with local ip machine)               
user        ----          public-ip:portA                                ----          Local-IP:portB
the protA is not same as portB, in this case what can i do if user want to access our STF server?

**Comment by sorccu** [comment]
In that case you can't use `stf local` since it doesn't expose all the
options you need. You would need to do a full deployment as described in
https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md.

**Comment by lincoln002** [comment]
vbanthia,First Thanks.

then, i have to say sorry. i have not describe my problems clearly. Actually, my network environment as follow:
            proxy machine(with public ip machine)             STF Server machine(with local ip machine)
user            ---- public-ip:portA                          ----                        Local-IP:portB
the protA is not same as portB, in this case what can i do if user want to access our STF server?

**Comment by bdliang** [comment]
@vbanthia 
 Hi , I tried to visit the stf service from public ip, so I use the following command to test it:
    
    stf local --public-ip x.x.x.x --poorxy-port 80 --websocket-port 80

I managed to set this up successfully and I'm able to connect to my Android phone via PC browser as well as controlling the the Android phone with no problem. The only thing that's odd is that there is no displaying in my PC's browser, all I got is a dark grey image of what's supposed to be the synchronized displaying of my Android phone's launcher. The image looks like this:

![qq 20160119151746](https://cloud.githubusercontent.com/assets/8120192/12412295/8085ae26-bec0-11e5-8af1-e095d3a021e0.png)

Do you have any idea of what's wrong? Thanks for any possible solutions.

**Comment by sorccu** [comment]
Most likely a firewall issue. Unless you do a full deployment, as mentioned earlier, the device screen goes through a different port which you must also open. In fact you have to open a whole range of ports for the screen. Either do a full deployment or tweak your firewall.

Also, many Windows machines don't like it when you use WebSockets on port 80. The connection tends to cut off after 10 seconds or so. I would recommend using a different port (ideally with HTTPS).

Anyway can't really help with the firewall issue. It's entirely up to you. You can check your developer console in your browser to see where it's trying to connect to. You have to then make sure that the connection to that address and port isn't being blocked by anything on either side.

OR this is a device that doesn't work yet. If so, consider becoming a [hardware sponsor](https://github.com/openstf/stf#sponsors-wanted) so that we can fix it for you.

**Comment by PanWangJ** [comment]
@sorccu It's quite likely a firewall issue, but isn't it much easier for us to just open those ports that stf needed for transferring device screens? So the problem now becomes what those ports are, do you have any idea what are they?

**Comment by sorccu** [comment]
You choose the range yourself or leave it as default, which is 15000-25000 (an overly large number but hey, at least it's large enough). See `stf local --help` or `stf provider --help` depending on your setup.

**Comment by Tanmoyray** [comment]
I am also gating the same issue on My macbook. I have also try to off my firewall but issue is still exit .

**Comment by rahul0698** [comment]
I am using stf on the local server and want to map that Ip with some domain(www.something.org) locally. Is it possible that when I hit that domain locally it won't redirect to and change URL in the browser to local Ip on which it is running. What changes to make in websocket index file and cli index file to make it work.

thanks in advance.

**Comment by sorccu** [comment]
Use the [deployment guide](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md). `stf local` is for local development only, though you may be able to use the `--public-ip` option to make it accessible from elsewhere. Can't help you with that, though.
