### ISSUE TITLE
Is there a different way to connect a Smartphone?

### ISSUE THREAD

**Issue by sacordova** [openstf/stf#262]
Hello guys,

i got a short question regarding Smartphone connection.

Is it possible to connect a Smartphone with the STF service via WiFi and not via USB?

If not yet, are you planing features like that?

P.S: I'm the succesor of Felix Hahn. He was already in contact with you.

Thanks.

**Comment by sorccu** [comment]
It's possible with `stf local --allow-remote`, but there's no point, and if you want to use it locally there are some drawbacks listed in the README. There are already many issues about this same thing but as a small recap:

The ADB wifi/TCP protocol is super inefficient and has huge overhead. If you try it yourself, without STF, you'll see a difference even with just regular `adb shell`. The latency and transfer speed can very easily drop to 1/10th (or less) of what you'd get with USB, which completely kills the STF screen performance.

Furthermore, many devices turn wifi off or at the very least disconnect from the network when they're idle, in order to conserve power. This means that your ADB connection will die all the time and someone will have to reconnect it.

Finally, you won't be able to test real 3G/4G or Airplane Mode if you connect your devices over wifi. You can't turn wifi off or choose another wifi network either.

So yeah. It's just not worth it in any sense.
