### ISSUE TITLE
Start stf from docker and get error: spawn adb ENOENT

### ISSUE THREAD

**Issue by labolado** [openstf/stf#282]
start stf from the docker 

`docker run -it -e RETHINKDB_PORT_28015_TCP='tcp://192.168.1.107:28015' openstf/stf  stf local --allow-remote`

get error: 
```
INF/provider 36 [*] Sending output to "tcp://127.0.0.1:7116"
INF/provider 36 [*] Receiving input from "tcp://127.0.0.1:7114"
Unhandled rejection Error: spawn adb ENOENT
    at exports._errnoException (util.js:849:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
INF/app 50 [*] Using pre-built resources
```

My system is Mac。

**Comment by vbanthia** [comment]
You are getting this error because you are doing it wrong. You are not supposed to run `stf local` from Docker. `stf local` was made for development purpose not for deployment. If you want full deployment using docker then follow this [Deployment doc](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md). It has everything you need for full deployment.

Anyways, the reason you are getting that error is because [STF docker image](https://github.com/openstf/docker-openstf-base/blob/master/Dockerfile) does not have `adb` in it. For `adb` it uses different image [docker-adb](https://github.com/sorccu/docker-adb/blob/master/Dockerfile). `stf local` requires `adb` to be installed and should be in `$PATH`.

One more thing, if you want to deploy stf using docker, I will not recommend to use OS X as it does not support docker natively. Use docker supported OS such as CentOS, Ubuntu etc.
