### ISSUE TITLE
Is there a doc about deploy stf on Win7

### ISSUE THREAD

**Issue by cdtdx** [openstf/stf#302]
I'm new to stf. After read the deploy doc , I found it will cost alot of time to deploy stf on Linux or Mac OS.
I wonder if there's an easy way to deploy stf on Win7(my pc os). And hopefully a detailed doc about all steps attached!

**Comment by sorccu** [comment]
None of the core developers uses Windows. It might be possible to make it work but we don't really care, to be honest. Our only officially supported deployment platform is Linux for now. 

Since you're asking for a very detailed guide, you could perhaps try posting a bounty on this issue, and maybe someone who knows how to do it will respond.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=32851453)](https://www.bountysource.com/issues/32851453-is-there-a-doc-about-deploy-stf-on-win7)
