### ISSUE TITLE
STF Production setup coreOS restart.

### ISSUE THREAD

**Issue by sj2208** [openstf/stf#335]
@sorccu - Need help regarding the production setup on coreOS:

I have done the production setup for STF on  4 coreOS machines. Now the major problem that i run into is that every other night one or the other COREOS machine restarts and the services restarts on other machines. I have to go and then edit the nginx.conf file with the updated end-points. 

Need to know if there is a way to disable the reboot for the machines ? or is there any stable way for production setup so that they don't bring the complete production setup down ?

Below are the setup details:

CoreOS version - stable 
I have coreOS machine with an entry for "reboot-strategy:off" in cloud config. 
coreos:
  update:
    reboot-strategy: off

**Comment by sorccu** [comment]
Our example deployment setup does not provide a solution for automatic service discovery, as there are simply too many solutions out there. A lazy method would be to use a MachineID condition in your fleet unit files to ensure they stay on the same machine.

As for the reboot, perhaps your cloud-config doesn't start with `#cloud-config`? It MUST start with that line or it will be ignored. Make the contents are properly indented too. Otherwise I'm not sure, other than that perhaps it's not reading the cloud config from the location you think it is. But that's a CoreOS question, not an STF question.

**Comment by sj2208** [comment]
Sure I agree that it belong to a COREOS problem, thought if you have some ideas to share on it. 

I validated my cloud-config at this [link](https://coreos.com/validate/) and it has no error.

I have made the changes to my unit files to run on the basis of machineID for now.  I saw your reply on the [thread](https://github.com/coreos/bugs/issues/161), so posted the question here. 
Thanks,
Closing this issue.

**Comment by sorccu** [comment]
Wow I haven't seen that validator tool before. Thanks for the link. Sorry for not being very useful, but right now spending time even responding to our own issues is essentially lost time, and therefore lost money to us. Hopefully it's understandable why we're not very interested in answering questions about unrelated projects.

**Comment by sj2208** [comment]
I completely understand  👍 
Will try to be precise about the issues from next time :) 

You have developed an amazing tool and its so helpful. Hoping for some new features \m/
