### ISSUE TITLE
Production setup -Devices show up on main page, but accessing them shows a grey page and cannot perform any action on it. 

### ISSUE THREAD

**Issue by sj2208** [openstf/stf#342]
@sorccu 

I have deployed stf in production mode on coreOS.
After starting all the services all devices start showing and are accessible. Now after 24 hours or so, 
few of the devices only show on screen and rest go in disconnected state ( Although the devices are connected to the same machines ). 
When i access a device in this state it shows up grey screen and on performing any action ( take screenshot ) it throws error. 
Have attached the screen-shots.  

When i restart the services, all devices start showing up again and are accessible.  Can you please guide me where can be the issue ? 

<img width="1437" alt="screen shot 2016-06-02 at 11 35 40 am" src="https://cloud.githubusercontent.com/assets/8023118/15735421/64103710-28b6-11e6-8c12-6c18c63041a1.png">
<img width="1436" alt="screen shot 2016-06-02 at 11 36 03 am" src="https://cloud.githubusercontent.com/assets/8023118/15735425/6e892ff8-28b6-11e6-9904-9dda0b94aed0.png">
<img width="1434" alt="screen shot 2016-06-02 at 11 40 15 am" src="https://cloud.githubusercontent.com/assets/8023118/15735469/ced29dae-28b6-11e6-9df5-da266b90293e.png">

**Comment by sorccu** [comment]
Looks like you've changed the STF logo (visible before you edited), meaning that you've modified the source code. Could be an issue you've created yourself.

I would suspect incorrect configuration.

**Comment by sj2208** [comment]
The changes was only the logo to check and deploy the changes with docker. 
At the time of starting units all devices starts showing up correctly. But after some time they go in some zombie state.

**Comment by vbanthia** [comment]
Most probably its related to TCP Connection timeout. It depends on how your local network is configured. 

One solution to solve this is by setting `ZMQ_TCP_KEEPALIVE` & `ZMQ_TCP_KEEPALIVE_IDLE` environment variable to your providers.

**Comment by sj2208** [comment]
@vbanthia - I have to pass them to providers only ?
Is below given unit file looks okay ?  

[Unit]
Description=STF app
After=rethinkdb-proxy-28015.service
BindsTo=rethinkdb-proxy-28015.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p-%i
ExecStartPre=-/usr/bin/docker rm %p-%i
ExecStart=/usr/bin/docker run --rm \
  --name %p-%i \
  --link rethinkdb-proxy-28015:rethinkdb \
  -e "SECRET=YOUR_SESSION_SECRET_HERE" \
  -e "ZMQ_TCP_KEEPALIVE =1" \
  -e "ZMQ_TCP_KEEPALIVE_IDLE =30000" \
  -p %i:3000 \
  openstf/stf:latest \
  stf app --port 3000 \
    --auth-url https://stf.example.org/auth/mock/ \
    --websocket-url https://stf.example.org/
ExecStop=-/usr/bin/docker stop -t 10 %p-%i

**Comment by vbanthia** [comment]
If you are running all other stf micro services such as (stf-app, stf-auth ...) in same machine then you only need to add these variable in provider. If you are using CoreOS + Fleet then they might be running on different machines then you will have to add these variables in other services(which are using zmq socket) too.

Basically you will have to make sure that all the TCP connections between your servers do not die.

**Comment by vbanthia** [comment]
looks like you have added some extra spaces in `-e "ZMQ_TCP_KEEPALIVE =1"`. It might not work because of that space. Change it to `-e "ZMQ_TCP_KEEPALIVE =1"` -> `-e "ZMQ_TCP_KEEPALIVE=1"`

Also, always write source code in markdown code block for better visibility.

**Comment by sj2208** [comment]
Thanks @vbanthia 
I am using COREOS + fleet

I have made the following changes
-e "ZMQ_TCP_KEEPALIVE=1" \
-e "ZMQ_TCP_KEEPALIVE_IDLE=30000" \
to the below unit-files
stf-triproxy-app
stf-triproxy-dev
stf-websocket
stf-provider@
stf-processor@


The setup works absolutely fine. But when i change the value  "ZMQ_TCP_KEEPALIVE_IDLE=30000" to 
 "ZMQ_TCP_KEEPALIVE_IDLE=600000" it starts  failing with the error in all above unit files with 
Invalid argument (tcp.cpp:121)

**Comment by sj2208** [comment]
@vbanthia  - please check if u get some time

**Comment by mitchtech** [comment]
Same issue here on my production deployment. Over time (usually a few hours), devices become inaccessible through the Control screen, but still show up as accessible in the main Devices list.  This issue is repeatable on both the master and v2.0.0 versions.

Adding the "ZMQ_TCP_KEEPALIVE=1" and "ZMQ_TCP_KEEPALIVE_IDLE=30000" environment variables to the systemd unit files did not seem to remedy the situation.

Not sure if this helps to diagnose the issue, but restarting only the provider services is sufficient for me to fully restore device access, but only to have the timeout occur again several hours later.

**Comment by vbanthia** [comment]
By definition TCP_KEEPIDLE is

> The time (in seconds) the connection needs to remain idle before TCP starts sending keepalive probes, if the socket option SO_KEEPALIVE has been set on this socket.

Can you guys try with `ZMQ_TCP_KEEPALIVE_IDLE=300`

**Comment by mitchtech** [comment]
Looking good so far passing 6 hours uptime with `ZMQ_TCP_KEEPALIVE_IDLE=300`. 

By now, without any direct interaction with STF, I would expect to see at least one provider start to become unresponsive. I'll follow up with on-going feedback since the issue intermittently took as long as ~48 hours idle to occur, but I expect this resolves the issue for me, thanks!

**Comment by sj2208** [comment]
Tried with  value ZMQ_TCP_KEEPALIVE_IDLE=300  and it failed after few hours again.

**Comment by mitchtech** [comment]
Four days uptime, all devices and providers still responsive. This definitely fixed the issue for me!

@sj2208  if the connection is still failing, I would try further reducing the value of `ZMQ_TCP_KEEPALIVE_IDLE`. Presumably the connection fails due to idle timeout; this will reduce the time period before the keepalive probes will start to fire to maintain the connection.

**Comment by sj2208** [comment]
Yep this is working. Thank you guys :) 👍   @vbanthia  @mitchtech  @sorccu

**Comment by tadesushilgithub** [comment]
Hi @sj2208,
Could you please tell me what is hardware configuration for the server? Can I connect 150 devices? I am planning to put production version on ubuntu 14 LTS.

**Comment by sanshaw1** [comment]
I have a ZMQ Pub sub connection. I want to send KeepAlive packet to my sub so that my sub does not disconnect after 40s . But i am not able to do it . Can someone please help me on this. I am using debian.
Below is the code that i have written : 

static void* pub_socket_init(const str_t* url, zmq_hwm_t zmq_hwm)
{
    zmq_socket_t socket;
    char* urlp;

    int tcp_keepalive = 1, tcp_keepalive_idle = 25;

    socket = zmq_socket(_zmq_context, ZMQ_PUB);
    if (!socket) {
        ERR(0, "zmq_socket(PUB): %s", ERRNO);
        return NULL;
    }

    if (zmq_setsockopt(socket, ZMQ_SNDHWM, &zmq_hwm, sizeof(zmq_hwm))) {
        ERR(0, "zmq_setsockopt(HWM): %s", ERRNO);
        return NULL;
    }

    if(zmq_setsockopt(socket, ZMQ_TCP_KEEPALIVE, &tcp_keepalive, sizeof(tcp_keepalive))) {
        ERR(0, "zmq_setsockopt(TCP): %s", ERRNO);
        INFO(0, "sanjay keepalive error -err %d", tcp_keepalive);
        return NULL;
    }
    else
    {
        INFO(0, "sanjay keepalive set -noerr %d", tcp_keepalive);
    }

    if(zmq_setsockopt(socket, ZMQ_TCP_KEEPALIVE_IDLE, &tcp_keepalive_idle, sizeof(tcp_keepalive_idle))) {
        ERR(0, "zmq_setsockopt(TCP): %s", ERRNO);
        INFO(0, "sanjay keepalive idle error -err %d", tcp_keepalive_idle);
        return NULL;
    }
    else
    {
        INFO(0, "sanjay idle set -noerr %d", tcp_keepalive_idle);
    }

 urlp = str2pchar(url);
    if (!urlp) {
        ERR(0, "Failed to copy url");
        return NULL;
    }

    if (zmq_bind(socket, urlp)) {
        ERR(0, "zmq_bind(PUB): %s", ERRNO);
        FREE(urlp);
        return NULL;
    }

    INFO(0, "PUB ENDPOINT started on %s", urlp);
    FREE(urlp);

    return socket;
}

**Comment by deg0nz** [comment]
Just want to confirm here, that this solved our issue too. Device providers are online for a loooong time now :)

**Comment by FRodero** [comment]
Hi!

How could I add environment variables on my STF system? Could you help me?

Thanks in advance!
