### ISSUE TITLE
STF production environment - On what hardware do you install?

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/stf#369]
## What's the problem (or question)?

I have 2 questions. 
1.Can we use a high end Server (HP Z640) with Ubuntu OR Mac Pro( Cylindrical Server)? which one is better?
2. If I install STF Local on a high end machine, will STF local handle 100 devices?  

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): 
* Version used (git hash or `stf -V`): 
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version: 
* If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here:

**Comment by sorccu** [comment]
The README includes all the hardware information we give away. We can't give you advice about your custom hardware because it's incredibly expensive and/or time consuming to do that. If you decide to use something else than what we have in the README, you are on your own (although you could perhaps use our consultation services for that if you wanted to). 

Anyway, a Mac Pro would be an incredibly bad idea. You would most likely be unable to handle anything more than 10-12 devices. You need to use PCIe USB cards or you're most likely screwed.
