### ISSUE TITLE
Why stf  is used rethinkdb?

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#378]
Why stf  is used rethinkdb not mysql/mongodb? What is the advantage of rethinkdb?

**Comment by sorccu** [comment]
I'm not going to get into a religious debate about databases. We felt like learning something new, and the fact that they provide official Node.js drivers was also a huge plus. It's written in modern C++ with SSD optimizations in mind from the start, and it boots up with just one command without any configuration whatsoever. And it comes with a built-in admin panel that's very usable and looks great.

The new real time functionality is also very interesting but it did not exist at the time.

If you'd like to use another database, you pretty much just need to rewrite one file, `lib/db/api.js`, so that's an option if you want to go through all the trouble.
