### ISSUE TITLE
Further plans for automated testing and STF

### ISSUE THREAD

**Issue by bgericke** [openstf/stf#387]
### What's the problem (or question)?

Hi,

first of all: Thanks for the API to @vbanthia, for the tests i have done yet, it works like a charm. What I could extract from the discussion in issue #219, STF seems to be planned currently as a device provider for automated tests with Appium (or other automation frameworks) via the REST API. 
Do you have any plans to make a deeper integration of automated tests into STF? Maybe for parallel testing?

We think about something like the following procedure to provide a convenient way for the test developer:

* write your test
* upload test to STF
* select multiple phones to run the test on and start test
* background service (maybe part of STF) does the following things:
     * start all the needed Appium Servers and reserve phones in STF
     * let appium servers make the tests
     * provide test results to the test developer

(Since we are only using Appium, i'll descriped it with Appium, but one could write such a feature more generic to add other automation frameworks later maybe...)

Greetings
Benjamin

**Comment by gunta** [comment]
Hi, yes we want to provide deeper integration like you describe.
Since most of the work can be done by using STF (instead of inside STF), a new repository would be expected for this integration. 
We are having time constraints right now, so any contribution would be very appreciated.

**Comment by bgericke** [comment]
Hey, thanks for the quick answer. 
What du you exactly mean by "new repository would be expected"?
Like some kind of "new project" which is afterwards used by STF?

**Comment by sorccu** [comment]
Since the current API exposes an ADB device, you can use or build any other
tool that requires an ADB connection. That new tool doesn't necessarily
have to be directly in the STF repository, STF just provides access to the
device. Depends on the use case, though.

**Comment by gunta** [comment]
Mostly yes, but this will depend on how much changes need to be made in the current STF code.

Since we currently don't know, but we want to make this work in an easy and straightforward way, I've created a new repository [here](https://github.com/openstf/stf-appium). 

Let's keep the discussion [there](https://github.com/openstf/stf-appium/issues/1) 
and any possible prototype for making this automation possible.

**Comment by ammartinho** [comment]
Hi, I'm trying to integrate Selenium Grid with OpenSTF, can you give me your opinion about what is the best way to do it? In the first plan, we thought of creating a module to merge the occupations of devices and thus prevent Selenium Grid to run a test on a device that is being used in OpenStf and the other way around.
Looking forward to know some opinions.

**Comment by gunta** [comment]
As a reference, in the past before developing STF we tried to use Selenium Grid as a backend but we had to drop it out because we found it to be unreliable. So we are not fans of Selenium Grid.

You might want also to try the [Jenkins plugin](https://wiki.jenkins-ci.org/display/JENKINS/Open+STF+Plugin). 

Other than that, if you're able to make it work, we would love to check it.

**Comment by koral--** [comment]
I see that this is quite old and closed issue but it seems to be the most appropriate place to submit links related to automated testing CI/using STF.

[Integration](https://github.com/DroidsOnRoids/bitrise-step-openstf-connect) for [bitrise.io](https://www.bitrise.io) is available. Parallel testing is also supported when [spoon Gradle plugin](https://github.com/stanfy/spoon-gradle-plugin) is used.

Blogpost with more info: https://www.thedroidsonroids.com/blog/how-to-connect-physical-devices-to-bitrise-io
