### ISSUE TITLE
Ask for help: How remote connect implement

### ISSUE THREAD

**Issue by codeskyblue** [openstf/stf#392]
There is a remote PC connected with a devices, I can use `adb devices` to see it.

```sh
$ adb devices
List of devices attached
S8GMTO7TT44P599S        device
```

Now in another PC, I can use `adb -H 10.0.0.2 devices` to list devices too, but each command executed are slowly(I guess it is because the network connect time cost). I have seen that with stf can do `adb connect 10.0.0.2:7001`

@sorccu Can please give some suggestions how to implement this? I want split out this feature from stf.

**Comment by sorccu** [comment]
Why does everyone want to do that now? This has been asked at least 5 times in the past week.

It's possible to do it and in fact it's quite easily exposed in one of our dependencies. A little bit of grepping will easily find it.

I can give advice if you're looking to improve STF or fix a bug, however since it sounds like you just want to rip one feature off, I'd prefer if you at least did the grepping yourself since we've done all the work for you already. Correct me if I'm wrong, though.

**Comment by codeskyblue** [comment]
I like to make stf better, and I have made some prs to stf already. But stf is very big, sometimes we only need some small part, Make it simple make it better to maintain it, also make it stable to use too. Stf's js code is some kind complex that hard to locate the real part, so it really helps to have your some suggestions.
Split it as a single tools will make this part code more rebust, it is also a way for me to make stf better.

**Comment by codeskyblue** [comment]
I can easily find it, but it is not easy at all when I see the implement code (need socket.js, packet.js) ...

**Comment by WillPangZi** [comment]
@codeskyblue Hi, do you implement is feature?
Actually I just want to use adb connect and without reserve the device?
It seems you have tried this. 
Any suggestions will be appreciated

**Comment by codeskyblue** [comment]
@WillPangZi you will know that 

```
npm install -g adbkit
adbkit -h
```

**Comment by WillPangZi** [comment]
@codeskyblue, awesome feature. Now I can share USB to network directly without fingerprint confirm.
But it seems when click the "Stop Using" button,  the adb share will be disconnected. I'm checking this point.
If you have any suggestions please let me know.
