### ISSUE TITLE
Can‘t use Screenshots

### ISSUE THREAD

**Issue by yuancc** [openstf/stf#46]
Hi,May I ask a question? When I click Screenshots, I can see a picture in the window of Screenshots , but I can't open the image when I click it,The new window will be prompted“The image http://localhost:7100/s/image/75eaef9a-0504-4a2c-8ffa-0d17ab1c3963/0e8bc602.jpg cannot be displayed because it contains errors”.
I have been troubled by the problem for several days,Looking forward to your answer,Thanks

**Comment by sorccu** [comment]
You most likely don't have GraphicsMagick installed (the `gm` command). It's listed in the requirements.

**Comment by rseek** [comment]
yuancc, hi, I had similar problem, so maybe my experience will help.
The problem was with GraphicsMagick indeed.
I installed it from source, following instructions on GraphicsMagick official site, and I faced exactly the same problem you are describing.
After I removed it and installed from my ubuntu repository, screenshots repaired.
https://github.com/openstf/stf/issues/20

**Comment by yuancc** [comment]
hi,sorccu and rseek,thanks for your reply! My problem has been solved by the method of rseek !
But now, I want to ask another question! How to set the rights of login?,everyone can login the platform of STF if he/she know my URL via his/her name and E-mail. In this case, there is a big security risk, where can I change it? Only through change from the source code ?

**Comment by sorccu** [comment]
You can use OAuth 2.0 or LDAP. Some information is available in [doc/DEPLOYMENT.md](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md). Note that you're not supposed to run STF with `stf local` in production, although it can be done. Here's my reply to someone else who asked privately:

-----------------------------------

As for authentication, what do you currently use? If you trust your developers enough that they're not going to claim to be someone else, you could just use the mock login while you're testing the system. Alternatively, we provide an implementation for LDAP and OAuth 2.0.

Although the processes are meant to be started separately, you COULD use either with of those with `stf local` like this:

```
stf local --auth-type oauth2 \
  --auth-options '[ 
    "--oauth-authorization-url", "https://sso.company.example.org/as/authorization.oauth2",
    "--oauth-token-url", "https://sso.company.example.org/as/token.oauth2",
    "--oauth-userinfo-url", "https://sso.company.example.org/idp/userinfo.openid",
    "--oauth-client-id", "YOUR_CLIENT_ID",
    "--oauth-client-secret", "YOUR_CLIENT_SECRET",
    "--oauth-callback-url", "https://stf.example.org/auth/oauth/callback",
    "--oauth-scope", "openid email"
  ]'
```

If that looks a bit weird, it's because it's not really meant to be super convenient - just possible.

You may also need to export NODE_TLS_REJECT_UNAUTHORIZED=0 in case you're using a self-signed cert. 

Similarly, you could support LDAP (or possibly ActiveDirectory) with the auth-ldap provider (or '--auth-type ldap` with `stf local`). Check `stf auth-ldap --help` for the available options.

We are planning on improving the documentation over time, however there are still a few bugs we want to fix first.

Also, be sure to read the Troubleshooting section of the README, especially if you're planning on using Intel processors, as you might find out you're only able to support 8-12 devices per machine otherwise!

Hope this gets you going for now.

**Comment by liuang68** [comment]
Hi,@sorccu good afternoon,paradon me,i need your help,my screenshots function doesn't working,i don't know why,the problem tip is 'http://localhost:7100/s/image/75eaef9a-0504-4a2c-8ffa-0d17ab1c3963/0e8bc602.jpg cannot be displayed because it contains errors' ,install GraphicsMagick ???how install ?can you give me a command?thx

**Comment by sorccu** [comment]
Read the README for installation instructions.

**Comment by liuang68** [comment]
@sorccu  i looked.but `````
 sudo npm install graphicsmagick
npm WARN lifecycle graphicsmagick@0.0.1~preinstall: cannot run in wd %s %s (wd=%s) graphicsmagick@0.0.1 node-waf clean || (exit 0); node-waf configure build /usr/local/lib/node_modules/stf/node_modules/.staging/graphicsmagick-e990271d
stf@2.3.0 /usr/local/lib/node_modules/stf
└── graphicsmagick@0.0.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by sorccu** [comment]
I can't help you with this. It's your responsibility to make your development environment work. The instructions provided in the README work. Nothing in the README says to run `sudo npm install graphicsmagick` so clearly you have not read it. You can't install it via npm. If you can't get it installed, consider using the docker image instead which includes (almost) everything.
