### ISSUE TITLE
Mirroring across multiple devices

### ISSUE THREAD

**Issue by amalChandran** [openstf/stf#492]
<Not a bug>

Is it possible to take touch events from one phone and mirror it across other phones? It might sound crazy but would be so usefull?

**Comment by sorccu** [comment]
Don't ping our usernames. This isn't twitter.

It is possible and we used to have a feature like that. However, it's more complex than you might think. If the devices are different in size or layout, what you touch on one device might end up touching something entirely else on another device. That's why the feature is not available anymore.

**Comment by amalChandran** [comment]
Oops sorry about that. 

Thanks for the quick reply.
