### ISSUE TITLE
screen capture and apk drag install FAIL (got HTTP 502)

### ISSUE THREAD

**Issue by xiaweixing** [openstf/stf#548]
**What is the issue or idea you have?**
screen capture and apk drag install FAIL
NOTE: I just restarted all services, so it seems it pulled the latest images and issues came out.  Before that, STF has been running for quite a long time (2-3 months) without above issues.  So, I'm not sure if it's caused by any upgrade? 
PS. I didn't change anything (.service files), just stop all services then start them.

Please help troubleshooting what the problem could be.  Thank you so much!

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
ALL devices

**Please provide the steps to reproduce the issue.**
use one device, click screenshot button, or drag an apk to install

**What is the expected behavior?**
screen capture/apk drag install PASS

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
It's in production env, with docker deployment. logs as below
```
IMP/device:plugins:connect 27 [7N2RDQ1472011083] Remote Connect Started for device "7N2RDQ1472011083" at "10.241.54.16:15013"
INF/device:plugins:screen:capture 27 [7N2RDQ1472011083] Capturing screenshot
ERR/device:support:storage 27 [7N2RDQ1472011083] Upload to "http://10.241.54.16/s/upload/image" failed: HTTP 502
ERR/device:plugins:screen:capture 27 [7N2RDQ1472011083] Screen capture failed Error: Upload to "http://10.241.54.16/s/upload/image" failed: HTTP 502
    at Request._callback (/app/lib/units/device/support/storage.js:29:27)
    at Request.self.callback (/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Please run `stf doctor` and paste the output here.**

**Comment by vbanthia** [comment]
This issue is related to this [PR](https://github.com/openstf/stf/pull/474). Previously, `--save-dir` option for storage service was not working. This PR allows to use `--save-dir` options to store all screenshot in persistent storage. 

You must be using [this](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md#stf-storage-tempservice) stf-storage unit file. This is using `--save-dir` as `/data` directory. `stf` user in docker container does not have root access so I am guessing that writing on `/data` directory is forbidden. One simple workaround is to delete `--save-dir /data` from your `stf-storage` unit file. or better solution will be to use a directory where `stf` user has write access.

**Comment by xiaweixing** [comment]
Thank you so much, @vbanthia !!
My problem is EXACTLY same as what you pointed out, after granting write permission of the directory, it works perfect now.

**Comment by sorccu** [comment]
Great, please close issues when solved :)
