### ISSUE TITLE
Questions when I start the .service units

### ISSUE THREAD

**Issue by yuancc** [openstf/stf#62]
Some questions generate when i start units.who can give me some suggestion to deal with it?
1.start the rethinkdb-proxy-28015.service unit,there is some problems like "/usr/bin/docker rm %p (code=exited, status=1/FAILURE)"
check status with the command "systemctl status rethinkdb-proxy-28015.service -l",then i can see

● rethinkdb-proxy-28015.service - RethinkDB proxy/28015
   Loaded: loaded (/etc/systemd/system/rethinkdb-proxy-28015.service; static; vendor preset: enabled)
   Active: active (running) since 一 2015-08-24 16:43:01 CST; 7min ago
  Process: 7911 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
  Process: 7903 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)

2.start the adbd.service unit(other units have the same questions)
check status with the command "systemctl status adbd.service -l",then i can see

 adbd.service - ADB daemon
   Loaded: loaded (/etc/systemd/system/adbd.service; static; vendor preset: enabled)
   Active: active (running) since 一 2015-08-24 17:09:51 CST; 2s ago
  Process: 15532 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
  Process: 15527 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)
  Process: 15401 ExecStartPre=/usr/bin/docker pull sorccu/adb:latest (code=exited, status=0/SUCCESS)
 Main PID: 15539 (docker)
   Memory: 1.7M
   CGroup: /system.slice/adbd.service
           └─15539 /usr/bin/docker run --rm --name adbd --privileged -v /dev/bus/usb:/dev/bus/usb --net host sorccu/adb:latest

 8月 24 17:09:32 OMTL docker[15401]: Pulling repository docker.io/sorccu/adb
 8月 24 17:09:35 OMTL docker[15401]: 37b4eb7ce7a3: Layer already being pulled by another client. Waiting.
 8月 24 17:09:51 OMTL docker[15401]: 37b4eb7ce7a3: Download complete
 8月 24 17:09:51 OMTL docker[15401]: Status: Image is up to date for sorccu/adb:latest
 8月 24 17:09:51 OMTL docker[15527]: Error response from daemon: Cannot kill container adbd: no such id: adbd
 8月 24 17:09:51 OMTL docker[15527]: Error: failed to kill containers: [adbd]
 8月 24 17:09:51 OMTL docker[15532]: Error response from daemon: no such id: adbd
 8月 24 17:09:51 OMTL docker[15532]: Error: failed to remove containers: [adbd]
 8月 24 17:09:51 OMTL systemd[1]: Started ADB daemon.
 8月 24 17:09:52 OMTL docker[15539]: OK

3.start the nginx.service unit(other units have the same questions)

 root@OMTL-STF:/etc# systemctl status nginx
● nginx.service - STF nginx public load balancer
   Loaded: loaded (/etc/systemd/system/nginx.service; static; vendor preset: enabled)
   Active: failed (Result: start-limit) since 一 2015-08-24 17:27:02 CST; 4s ago
  Process: 31651 ExecStop=/usr/bin/docker stop -t 2 %p (code=exited, status=1/FAILURE)
  Process: 31638 ExecStart=/usr/bin/docker run --rm --name %p --net host -v /home/yuancc/ssl.crt:/etc/nginx/ssl/ssl.crt:ro -v /home/yuancc/ssl.key:/etc/nginx/ssl/ssl.key:ro -v /home/yuancc/ssl.pfx:/etc/nginx/ssl/ssl.pfx:ro -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro nginx:1.7.10 nginx (code=exited, status=1/FAILURE)
  Process: 31632 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
  Process: 31625 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)
  Process: 31692 ExecStartPre=/usr/bin/docker pull nginx:1.7.10 (code=exited, status=1/FAILURE)
 Main PID: 31638 (code=exited, status=1/FAILURE)

 8月 24 17:27:02 OMTL-STF systemd[1]: Failed to start STF nginx public load balancer.
 8月 24 17:27:02 OMTL-STF systemd[1]: Unit nginx.service entered failed state.
 8月 24 17:27:02 OMTL-STF systemd[1]: nginx.service failed.
 8月 24 17:27:02 OMTL-STF systemd[1]: nginx.service holdoff time over, scheduling restart.
 8月 24 17:27:02 OMTL-STF systemd[1]: start request repeated too quickly for nginx.service
 8月 24 17:27:02 OMTL-STF systemd[1]: Failed to start STF nginx public load balancer.
 8月 24 17:27:02 OMTL-STF systemd[1]: Unit nginx.service entered failed state.
 8月 24 17:27:02 OMTL-STF systemd[1]: nginx.service failed.

**Comment by sorccu** [comment]
Sorry for the late response. The deployment docs unfortunately had many mistakes (see #76 if interested) and were updated a while ago to be more complete. Closing this ticket for now.

**Comment by rahul0698** [comment]
I am having some problem in running stf-app@.service, stf-migrate.service, stf-reaper.service


status of services..
●  stf-websocket@3600.service - STF websocket
   Loaded: loaded (/etc/systemd/system/stf-websocket@.service; static; vendor preset: enabled)
  Drop-In: /etc/systemd/system/stf-websocket@.service.d
           └─override.conf
   Active: inactive (dead)

Jul 04 16:01:52 linux-rahul docker[30612]: FTL/db 1 [*] No hosts left to try
Jul 04 16:01:52 linux-rahul docker[30612]: FTL/util:lifecycle 1 [*] Shutting down due to fatal error
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Main process exited, code=exited, status=1/FAILURE
Jul 04 16:01:52 linux-rahul docker[30766]: Error response from daemon: No such container: stf-websocket-3600
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Control process exited, code=exited status=1
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Unit entered failed state.
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Failed with result 'exit-code'.
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Service hold-off time over, scheduling restart.
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Stop job pending for unit, delaying automatic rest
Jul 04 16:01:52 linux-rahul systemd[1]: Stopped STF websocket.
lines 1-16/16 (END)

● stf-reaper.service - STF reaper
   Loaded: loaded (/etc/systemd/system/stf-reaper.service; static; vendor preset: enabled)
  Drop-In: /etc/systemd/system/stf-reaper.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Tue 2017-07-04 16:08:18 IST; 3s ago
  Process: 31367 ExecStop=/usr/bin/docker stop -t 10 %p (code=exited, status=0/SUCCESS)
  Process: 31348 ExecStop=/usr/bin/docker stop -t 10 %p (code=exited, status=0/SUCCESS)
  Process: 31200 ExecStart=/usr/bin/docker run --rm --name %p --link rethinkdb-proxy-28015:rethinkdb openstf/stf:lates
  Process: 31192 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
  Process: 31183 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)
  Process: 31174 ExecStartPre=/usr/bin/docker pull openstf/stf:latest (code=exited, status=0/SUCCESS)
  Process: 31166 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
  Process: 31158 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)
  Process: 31151 ExecStartPre=/usr/bin/docker pull openstf/stf:latest (code=exited, status=0/SUCCESS)
 Main PID: 31200 (code=exited, status=1/FAILURE)

Jul 04 16:08:17 linux-rahul docker[31200]: INF/db 1 [dev] Unable to connect to 172.17.0.7:28015
Jul 04 16:08:17 linux-rahul docker[31200]: FTL/db 1 [dev] No hosts left to try
Jul 04 16:08:17 linux-rahul docker[31200]: FTL/util:lifecycle 1 [dev] Shutting down due to fatal error
Jul 04 16:08:18 linux-rahul systemd[1]: Stopping STF reaper...
Jul 04 16:08:18 linux-rahul docker[31348]: stf-reaper
Jul 04 16:08:18 linux-rahul docker[31367]: stf-reaper
Jul 04 16:08:18 linux-rahul systemd[1]: stf-reaper.service: Main process exited, code=exited, status=1/FAILURE

● stf-app@3100.service - STF app
   Loaded: loaded (/etc/systemd/system/stf-app@.service; static; vendor preset: enabled)
  Drop-In: /etc/systemd/system/stf-app@.service.d
           └─override.conf
   Active: inactive (dead)

Jul 04 15:44:13 linux-rahul docker[29378]: INF/app 1 [*] Using pre-built resources
Jul 04 15:44:13 linux-rahul docker[29378]: INF/app 1 [*] Listening on port 3000
Jul 04 15:44:13 linux-rahul docker[29378]: INF/db 1 [*] Connecting to 172.17.0.7:28015
Jul 04 15:44:14 linux-rahul docker[29378]: INF/db 1 [*] Unable to connect to 172.17.0.7:28015
Jul 04 15:44:14 linux-rahul docker[29378]: FTL/db 1 [*] No hosts left to try
Jul 04 15:44:14 linux-rahul docker[29378]: FTL/util:lifecycle 1 [*] Shutting down due to fatal error
Jul 04 15:44:14 linux-rahul systemd[1]: Stopping STF app...
Jul 04 15:44:14 linux-rahul docker[29536]: stf-app-3100
Jul 04 15:44:14 linux-rahul docker[29552]: stf-app-3100
Jul 04 15:44:14 linux-rahul systemd[1]: Stopped STF app.


my other services that are needed for these service to work are running

CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                                        NAMES
6f473dd263b7        openstf/ambassador:latest   "/run.sh"                33 minutes ago      Up 33 minutes       0.0.0.0:32769->28015/tcp                                                     rethinkdb-proxy-28015
162a96d3b7b2        openstf/stf:latest          "stf auth-mock --port"   48 minutes ago      Up 48 minutes       0.0.0.0:3200->3000/tcp                                                       stf-auth-3200
f5f11e62a352        rethinkdb:2.3.5             "rethinkdb --bind all"   2 hours ago         Up 2 hours          0.0.0.0:8080->8080/tcp, 0.0.0.0:28015->28015/tcp, 0.0.0.0:29015->29015/tcp   rethinkdb
cab4b8344e50        openstf/stf:latest          "stf triproxy dev --b"   2 hours ago         Up 2 hours                                                                                       stf-triproxy-dev
0bcda7b6a11f        openstf/stf:latest          "stf triproxy app --b"   2 hours ago         Up 2 hours                                                                                       stf-triproxy-app
e62202bbfe23        openstf/stf:latest          "stf storage-plugin-i"   2 hours ago         Up 2 hours          0.0.0.0:3500->3000/tcp                                                       stf-storage-temp-3500
ac9926857cc6        openstf/stf:latest          "stf storage-plugin-i"   2 hours ago         Up 2 hours          0.0.0.0:3400->3000/tcp                                                       stf-storage-plugin-image-3400
1a95bacdeefb        openstf/stf:latest          "stf storage-plugin-a"   2 hours ago         Up 2 hours          0.0.0.0:3300->3000/tcp                                                       stf-storage-plugin-apk-3300
d7ac389ce7f6        openstf/stf:latest          "stf provider --name "   2 hours ago         Up 2 hours                                                                                       stf-provider-floor8
877bde7a6f16        openstf/stf:latest          "stf provider --name "   2 hours ago         Up 2 hours                                                                                       stf-provider-floor4
1a2441bcf8a9        sorccu/adb:latest           "/sbin/tini -- adb -a"   2 hours ago         Up 2 hours                                                                                       adbd


I am not able to figure out what is the problem here, please guide. Thanks in advance

**Comment by vbanthia** [comment]
Here is the error logs
> Jul 04 16:08:17 linux-rahul docker[31200]: INF/db 1 [dev] Unable to connect to 172.17.0.7:28015
Jul 04 16:08:17 linux-rahul docker[31200]: FTL/db 1 [dev] No hosts left to try

Either your db is not running or your unit files are not configured properly.

**Comment by rahul0698** [comment]
@vbanthia  sorry to bother you once again.

here are my rethinkdb  and rethinkdb-proxy-28015 service that is actively running 
● rethinkdb.service - RethinkDB
   Loaded: loaded (/etc/systemd/system/rethinkdb.service; static; vendor preset: enabl
  Drop-In: /etc/systemd/system/rethinkdb.service.d
           └─override.conf
   Active: active (running) since Wed 2017-07-05 11:22:27 IST; 6h ago
 Main PID: 20411 (docker)
    Tasks: 7
   Memory: 4.3M
      CPU: 83ms
   CGroup: /system.slice/rethinkdb.service
           └─20411 /usr/bin/docker run --rm --name rethinkdb -v /srv/rethinkdb:/data -

Jul 05 11:22:29 linux-rahul docker[20411]: Running on Linux 4.4.0-81-generic x86_64
Jul 05 11:22:29 linux-rahul docker[20411]: Loading data from directory /data/rethinkdb
Jul 05 11:22:29 linux-rahul docker[20411]: warn: Cache size is larger than available m
Jul 05 11:22:29 linux-rahul docker[20411]: Listening for intracluster connections on p
Jul 05 11:22:29 linux-rahul docker[20411]: Listening for client driver connections on 
Jul 05 11:22:29 linux-rahul docker[20411]: Listening for administrative HTTP connectio
Jul 05 11:22:34 linux-rahul docker[20411]: Listening on cluster addresses: 127.0.0.1, 
Jul 05 11:22:35 linux-rahul docker[20411]: Listening on driver addresses: 127.0.0.1, 1
Jul 05 11:22:35 linux-rahul docker[20411]: Listening on http addresses: 127.0.0.1, 172
Jul 05 11:22:35 linux-rahul docker[20411]: Server ready, "090e939c8a09_xbn" f1a073ee-e
lines 1-22/22 (END)


● rethinkdb-proxy-28015.service - RethinkDB proxy/28015
   Loaded: loaded (/etc/systemd/system/rethinkdb-proxy-28015.service; static; vendor p
  Drop-In: /etc/systemd/system/rethinkdb-proxy-28015.service.d
           └─override.conf
   Active: active (running) since Wed 2017-07-05 12:20:16 IST; 5h 14min ago
  Process: 22941 ExecStop=/usr/bin/docker stop -t 10 %p (code=exited, status=1/FAILURE
  Process: 22929 ExecStop=/usr/bin/docker stop -t 10 %p (code=exited, status=1/FAILURE
  Process: 23019 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
  Process: 23011 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)
  Process: 23001 ExecStartPre=/usr/bin/docker pull openstf/ambassador:latest (code=exi
  Process: 22992 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
  Process: 22984 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)
  Process: 22964 ExecStartPre=/usr/bin/docker pull openstf/ambassador:latest (code=exi
 Main PID: 23028 (docker)
    Tasks: 7
   Memory: 4.0M
      CPU: 66ms
   CGroup: /system.slice/rethinkdb-proxy-28015.service
           └─23028 /usr/bin/docker run --rm --name rethinkdb-proxy-28015 -e AUTHKEY= -

Jul 05 12:20:16 linux-rahul docker[23001]: a3ed95caeb02: Already exists
Jul 05 12:20:16 linux-rahul docker[23001]: 2574e0aab087: Already exists
Jul 05 12:20:16 linux-rahul docker[23001]: bdb8e229719e: Already exists

and my config file is
1. rethinkdb.service
[Unit]
Description=RethinkDB
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull rethinkdb:2.3.5
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStartPre=/usr/bin/chattr -R +C /srv/rethinkdb
ExecStart=
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  -v /srv/rethinkdb:/data \
  -e "AUTHKEY=" \
  -p 8080:8080 \
  -p 28015:28015 \
  -p 29015:29015 \
  rethinkdb:2.3.5 \
  rethinkdb --bind all --canonical-address 192.168.104.183 \
    --cache-size 8192
ExecStop=-/usr/bin/docker stop -t 10 %p


2. rethinkdb-proxy-28015.service

[Unit]
Description=RethinkDB proxy/28015
After=docker.service rethinkdb.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/ambassador:latest
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStart=
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  -e "AUTHKEY=" \
  -p 28015 \
  -e RETHINKDB_PORT_28015_TCP=tcp://rethinkdb.stf.example.org:28015 \
  openstf/ambassador:latest
ExecStop=-/usr/bin/docker stop -t 10 %p


I have removed the environment variable as I haven't set the authorisation key for rethinkdb as suggested by @sorccu in #56 
and also I am able to open web UI at 192.186.104.183:8080
but still the error in stf-app@3100.service occur which require rethinkdb-proxy-28015.service, please help.Thanks in advance!

 
here is the status of stf-app@3100.service
● stf-app@3100.service - STF app
   Loaded: loaded (/etc/systemd/system/stf-app@.service; static; vendor preset: enabled)
  Drop-In: /etc/systemd/system/stf-app@.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Wed 2017-07-05 17:45:47 IST; 15s ago
  Process: 27129 ExecStop=/usr/bin/docker stop -t 10 %p-%i (code=exited, status=0/SUCCESS)
  Process: 27110 ExecStop=/usr/bin/docker stop -t 10 %p-%i (code=exited, status=0/SUCCESS)
  Process: 26950 ExecStart=/usr/bin/docker run --rm --name %p-%i --link rethinkdb-proxy-28015
  Process: 26941 ExecStartPre=/usr/bin/docker rm %p-%i (code=exited, status=1/FAILURE)
  Process: 26932 ExecStartPre=/usr/bin/docker kill %p-%i (code=exited, status=1/FAILURE)
  Process: 26923 ExecStartPre=/usr/bin/docker pull openstf/stf:latest (code=exited, status=0/
  Process: 26915 ExecStartPre=/usr/bin/docker rm %p-%i (code=exited, status=1/FAILURE)
  Process: 26907 ExecStartPre=/usr/bin/docker kill %p-%i (code=exited, status=1/FAILURE)
  Process: 26897 ExecStartPre=/usr/bin/docker pull openstf/stf:latest (code=exited, status=0/
 Main PID: 26950 (code=exited, status=1/FAILURE)

Jul 05 17:45:46 linux-rahul docker[26950]: INF/db 1 [*] Unable to connect to 172.17.0.3:28015
Jul 05 17:45:46 linux-rahul docker[26950]: FTL/db 1 [*] No hosts left to try
Jul 05 17:45:46 linux-rahul docker[26950]: FTL/util:lifecycle 1 [*] Shutting down due to fata
Jul 05 17:45:47 linux-rahul systemd[1]: Stopping STF app...
Jul 05 17:45:47 linux-rahul docker[27110]: stf-app-3100
Jul 05 17:45:47 linux-rahul docker[27129]: stf-app-3100
Jul 05 17:45:47 linux-rahul systemd[1]: stf-app@3100.service: Main process exited, code=exite
lines 1-23

**Comment by sorccu** [comment]
`RETHINKDB_PORT_28015_TCP=tcp://rethinkdb.stf.example.org:28015` is this the exact line you have in there?

**Comment by rahul0698** [comment]
where?  in rethinkdb-proxy-28015 unit ?? 

yes it is the exact line

**Comment by sorccu** [comment]
Have you thought about replacing it with the real address of the rethinkdb
server?

**Comment by rahul0698** [comment]
sorry to bother you again and again.
after replacing the rethinkdb.stf.example.org in rethinkdb-proxy-28015 unit with  an address of rethinkdb server and then running the stf-app@3100.service unit I got the following error

● stf-app@3100.service - STF app
   Loaded: loaded (/etc/systemd/system/stf-app@.service; static; vendor preset: enabled)
  Drop-In: /etc/systemd/system/stf-app@.service.d
           └─override.conf
   Active: activating (start-pre) since Wed 2017-07-05 18:34:45 IST; 6s ago
  Process: 30472 ExecStop=/usr/bin/docker stop -t 10 %p-%i (code=exited, status=1/FAILURE)
  Process: 30465 ExecStop=/usr/bin/docker stop -t 10 %p-%i (code=exited, status=1/FAILURE)
  Process: 30346 ExecStart=/usr/bin/docker run --rm --name %p-%i --link rethinkdb-proxy-28015:rethinkdb -e SECRET= -p %i:3000 openstf/stf:lates
  Process: 30338 ExecStartPre=/usr/bin/docker rm %p-%i (code=exited, status=1/FAILURE)
  Process: 30510 ExecStartPre=/usr/bin/docker pull openstf/stf:latest (code=exited, status=0/SUCCESS)
  Process: 30501 ExecStartPre=/usr/bin/docker rm %p-%i (code=exited, status=1/FAILURE)
  Process: 30493 ExecStartPre=/usr/bin/docker kill %p-%i (code=exited, status=1/FAILURE)
  Process: 30483 ExecStartPre=/usr/bin/docker pull openstf/stf:latest (code=exited, status=0/SUCCESS)
 Main PID: 30346 (code=exited, status=1/FAILURE);         : 30518 (docker)
   CGroup: /system.slice/system-stf\x2dapp.slice/stf-app@3100.service
           └─control
             └─30518 /usr/bin/docker kill stf-app-3100

Jul 05 18:34:45 linux-rahul systemd[1]: Starting STF app...
Jul 05 18:34:49 linux-rahul docker[30483]: latest: Pulling from openstf/stf
Jul 05 18:34:49 linux-rahul docker[30483]: Digest: sha256:2a81ec596c46e979cb4663e80c063ae76f3207c50ad704ed3946793c496bfa5d
Jul 05 18:34:49 linux-rahul docker[30483]: Status: Image is up to date for openstf/stf:latest
Jul 05 18:34:49 linux-rahul docker[30493]: Error response from daemon: Cannot kill container stf-app-3100: No such container: stf-app-3100
Jul 05 18:34:49 linux-rahul docker[30501]: Error response from daemon: No such container: stf-app-3100
Jul 05 18:34:52 linux-rahul docker[30510]: latest: Pulling from openstf/stf
Jul 05 18:34:52 linux-rahul docker[30510]: Digest: sha256:2a81ec596c46e979cb4663e80c063ae76f3207c50ad704ed3946793c496bfa5d
Jul 05 18:34:52 linux-rahul docker[30510]: Status: Image is up to date for openstf/stf:latest


here is the unit file config of rethinkdb-proxy-28015.service

[Unit]
Description=RethinkDB proxy/28015
After=docker.service rethinkdb.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/ambassador:latest
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStart=
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  -e "AUTHKEY=" \
  -p 28015 \
  -e RETHINKDB_PORT_28015_TCP=tcp://192.168.104.183:28015 \
  openstf/ambassador:latest
ExecStop=-/usr/bin/docker stop -t 10 %p

**Comment by sorccu** [comment]
Please use ``` to format your code. If you don't do that, it looks bad and some characters may not be shown at all, like `\`. 

I don't see anything relevant in that log. Perhaps you cut it a bit short.

**Comment by rahul0698** [comment]
once again I am sorry to bother. 
As suggested by @sorccu  I have replaced the domain name stf.example.org by the actual IP address and my rethinkdb and rethinkdb-proxy-28015 are working fine and even stf-app@3100 and stf-websocket@.service are actively running. Now only one service is left that is stf-migrate.service which is not working correctly and getting failed. 

Here is the status of the stf-migrate.service
```
● stf-migrate.service - STF migrate
   Loaded: loaded (/etc/systemd/system/stf-migrate.service; static; vendor preset: enabled)
  Drop-In: /etc/systemd/system/stf-migrate.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Thu 2017-07-06 15:53:11 IST; 2h 2min ago
 Main PID: 3449 (code=exited, status=1/FAILURE)

Jul 06 15:53:07 linux-rahul docker[3432]: Error response from daemon: Cannot kill container stf-migrate: No such container: stf-migrate
Jul 06 15:53:07 linux-rahul docker[3441]: Error response from daemon: No such container: stf-migrate
Jul 06 15:53:10 linux-rahul docker[3449]: INF/db 1 [*] Connecting to 172.17.0.3:28015
Jul 06 15:53:10 linux-rahul docker[3449]: INF/db 1 [*] Unable to connect to 172.17.0.3:28015
Jul 06 15:53:10 linux-rahul docker[3449]: FTL/db 1 [*] No hosts left to try
Jul 06 15:53:10 linux-rahul docker[3449]: FTL/util:lifecycle 1 [*] Shutting down due to fatal error
Jul 06 15:53:11 linux-rahul systemd[1]: stf-migrate.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 15:53:11 linux-rahul systemd[1]: Failed to start STF migrate.
Jul 06 15:53:11 linux-rahul systemd[1]: stf-migrate.service: Unit entered failed state.
Jul 06 15:53:11 linux-rahul systemd[1]: stf-migrate.service: Failed with result 'exit-code'.
```

and here is the unit file config of stf-migrate 

[Unit]
Description=STF migrate
After=rethinkdb-proxy-28015.service
BindsTo=rethinkdb-proxy-28015.service

[Service]
Type=oneshot
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  --link rethinkdb-proxy-28015:rethinkdb \
  openstf/stf:latest \
  stf migrate

since it depends on rethinkdb-proxy-28015.service and which is working fine, could not figure out why it is getting failed. Please guide. Thanks in advance
