### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by liuchang6** [openstf/stf#628]
I tried using docker to start STF

docker run -d --name stf --net host openstf/stf stf local --public-ip 192.168.255.130
![bxt rc58ah2xh5 swo a](https://user-images.githubusercontent.com/25145380/27326823-29fc9c4c-55df-11e7-81a6-db4935a26a9a.png)

There was an error accessing the 192.168.255.130:7100
HTTP ERROR 503
Would you please help me with this problem?

**Comment by sorccu** [comment]
At the very least, you should have posted the exact error from the error log, or preferably the full log. You have also removed the issue template where we ask you to provide these details so that we don't have to ask you every time, which wastes our time.

In general, we don't support `stf local` deployments, it takes too much time. It's a development version. Please consider doing a [full deployment](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) instead. This is the ONLY deployment we support, and ONLY if you've followed it 100%.

Note that `stf local` can work with the correct options (assuming the other containers have correct options too), however we won't help you with that.

Also, you're using boot2docker which is 100% more trouble. Not recommended.
