### ISSUE TITLE
Support Android 7.0 +?

### ISSUE THREAD

**Issue by NextOneWxf** [openstf/stf#639]
Support Android 7.0 +?

**Comment by sorccu** [comment]
No idea what you're asking.

**Comment by sorccu** [comment]
Ok. For Android 7.0, don't install STF from npm. Build latest master. It works fine.

**Comment by NextOneWxf** [comment]
I was run it by Docker, the images from Docker.io is latest?

**Comment by sorccu** [comment]
Did you use the :latest tag?

**Comment by NextOneWxf** [comment]
yes.i think so.
![image](https://user-images.githubusercontent.com/4550421/27771361-b8469a4e-5f7f-11e7-8cb8-e0a0d56a523e.png)
![image](https://user-images.githubusercontent.com/4550421/27771392-2da65270-5f80-11e7-90dc-7057eed566fe.png)

But now,my run the STF just like that,how can i connect the  Android 7.0 device without Root use the USB?

**Comment by sorccu** [comment]
It sounds like perhaps your issue is not with Android 7.0, but rather you
don't know how to connect a device.

Perhaps you're running STF in a virtual machine and need to add the device
there? Not enough details. What you should do is tell us what exactly you
did. You have to tell what your setup is like. You have to tell which
commands you used.

**Comment by NextOneWxf** [comment]
![image](https://user-images.githubusercontent.com/4550421/27771899-a3067e6e-5f8a-11e7-9a1d-b214b9c133e7.png)
ok，i make a mistakes。Now I can run it。Thanks a lot.
the last question：Will support  Apple devices  later?

**Comment by sorccu** [comment]
Perhaps some day, but we're super busy with other things now.

**Comment by NextOneWxf** [comment]
ok~
