### ISSUE TITLE
AndroidTV FireTV support

### ISSUE THREAD

**Issue by hosek** [openstf/stf#686]
**Option for connecting devices via adb connect from STF**
Hi,
I would like to connect some AndroidTVs and FireTVs to STF, but Im missing option to connect  device just via IP address. Do you plan to add this option?
Or if you can point me to the right module, I can try to add it.

Thank you in advance!

**Comment by sorccu** [comment]
I would recommend using an USB cable instead as you may get horrible performance otherwise, but you can do that by starting STF with the `--allow-remote` option and then issuing a standard `adb connect` command after that. STF will then pick up the device.

Please close the ticket if this resolves your issue.

**Comment by hosek** [comment]
Ok Thanks!
