### ISSUE TITLE
Connecting to RethinkDB

### ISSUE THREAD

**Issue by MichaelMadsen** [openstf/stf#76]
Sorry to keep spamming this forum, but I seem to be really close to having the complete system working. All services are in the green and everything seems to communicate like it should... Except for the database connection, so that's quite an important link I'm missing.

Here's my setup:

1. A Ubuntu Server 15 VM (192.168.99.**107**) running RethinkDB in a docker container, and an ambassador exposing it to the world.

rethinkdb.service
```
[Unit]
Description=RethinkDB
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull sorccu/rethinkdb:1.15.2
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  sorccu/rethinkdb:1.15.2
ExecStop=-/usr/bin/docker stop -t 10 %p
```

rethinkdb-ambassador.service
```
[Unit]
Description=RethinkDB ambassador
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/ambassador:latest
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  --link rethinkdb:rethinkdb \
  -p 28015:28015 \
  openstf/ambassador:latest
ExecStop=-/usr/bin/docker stop -t 10 %p
```

2. A Ubuntu Server 15 VM (192.168.99.**106**) running the rest of the stf services, and a rethinkdb-proxy-28015.service to make the database connection 

rethinkdb-proxy-28015.service
```
[Unit]
Description=RethinkDB proxy/28015
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/ambassador:latest
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  -e "AUTHKEY=1234" \
  -p 28015 \
  -e RETHINKDB_PORT_28015_TCP=tcp://192.168.99.107:28015 \
  openstf/ambassador:latest
ExecStop=-/usr/bin/docker stop -t 10 %p
```

To test it I try running the stf-migrate.service
```
[Unit]
Description=STF migrate
After=rethinkdb-proxy-28015.service
BindsTo=rethinkdb-proxy-28015.service

[Service]
EnvironmentFile=/etc/environment
Type=oneshot
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  --link rethinkdb-proxy-28015:rethinkdb \
  openstf/stf:latest \
  stf migrate
```

Now, from the client, I can do wget 192.168.99.107:28015 and receive the index.html explaining "this is a rethinkdb port, you are connecting wrong". So I know that the address is open and accessible, so the ambassador is working its part.

However, trying to launch stf-migrate (or any other service connecting to the rethinkdb-proxy), this happens:
```
Sep 09 10:34:08 ubuntu docker[17758]: INF/db 1 [*] Connecting to 172.17.7.85:28015
Sep 09 10:34:08 ubuntu docker[17758]: INF/db 1 [*] Unable to connect to 172.17.7.85:28015
Sep 09 10:34:08 ubuntu docker[17758]: FTL/db 1 [*] No hosts left to try
Sep 09 10:34:08 ubuntu docker[17758]: FTL/util:lifecycle 1 [*] Shutting down due to fatal error
Sep 09 10:34:09 ubuntu systemd[1]: stf-migrate.service: main process exited, code=exited, status=1/FAILURE
```
So stf-migrate tries to connect to the rethinkdb-proxy-28015.service docker container, and fails. The problem seems to be entirely local on the second machine, since the ambassador seems to work perfectly. The services cannot connect to the proxy properly, but I cannot figure out where the problem comes from.

**Comment by sorccu** [comment]
Hi,

You seem to be using my old rethinkdb image. I made it when there was no official rethinkdb image available yet, and we are not using it anymore. It's not supposed to be in our docs, how did you find it? I won't remove it in case someone's still using it, but I just added deprecation notice to the repo to prevent this from happening again.

It's possible that your connection problems are caused by the driver being too new for the old image, but more likely it's a problem with the `--canonical-address` flag.

Additionally, with your current config you'll lose your data when the container shuts down.

Here's our unit (but you may want to at least update the rethinkdb version):

```systemd
[Unit]
Description=RethinkDB
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull rethinkdb:2.0.4
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStartPre=/usr/bin/mkdir -p /srv/rethinkdb
ExecStartPre=/usr/bin/chattr -R +C /srv/rethinkdb
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  -v /srv/rethinkdb:/data \
  -e "AUTHKEY=YOUR_AUTHKEY_HERE" \
  -p 8080:8080 \
  -p 28015:28015 \
  -p 29015:29015 \
  rethinkdb:2.0.4 \
  rethinkdb --bind all --canonical-address ${COREOS_PRIVATE_IPV4} \
    --cache-size 8192
ExecStop=-/usr/bin/docker stop -t 10 %p
```

Note that we are NOT running the ambassador on the database host itself, although you can certainly do it that way if you like.

Alternatively if you find specifying the `--canonical-address` annoying, you could just use host networking and it should bind to the right address.

```systemd
[Unit]
Description=RethinkDB
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull rethinkdb:2.0.4
ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p
ExecStartPre=/usr/bin/mkdir -p /srv/rethinkdb
ExecStartPre=/usr/bin/chattr -R +C /srv/rethinkdb
ExecStart=/usr/bin/docker run --rm \
  --name %p \
  -v /srv/rethinkdb:/data \
  -e "AUTHKEY=YOUR_AUTHKEY_HERE" \
  --net host \
  rethinkdb:2.0.4 \
  rethinkdb --bind all \
    --cache-size 8192
ExecStop=-/usr/bin/docker stop -t 10 %p
```

**Comment by sorccu** [comment]
Also... if you do set an auth key, you'll have to open the web UI the first time and run

```javascript
r.db('rethinkdb').table('cluster_config').get('auth').update({auth_key: 'newkey'})
```

As per https://rethinkdb.com/docs/security/. It used to be possible to do it from the command line more easily.

**Comment by MichaelMadsen** [comment]
I was just trying different things in desperation, trying to get it to work. Found your rethinkdb docker container via your docker account, presumed it was the one you were using. I've changed it to the official one now.

The problem turned out to be the auth key. Now I can connect to the database server. Thanks a lot!

Now all the services seem to be running and communicating with each other.
Only problem left is accessing the webpage. Trying to connect to the ip gives a 502 Bad Gateway, and the log for nginx.service shows, I think, that it doesn't get a response from the stf-app@3100.service:

```
Sep 09 12:46:03 ubuntu docker[15216]: 192.168.99.1 - - [09/Sep/2015:11:46:03 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
Sep 09 12:46:03 ubuntu docker[15216]: 2015/09/09 11:46:03 [error] 6#0: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.99.1, server: 192.168.99.106, request: "GET / HTTP/1.1", upstream: "http://192.168.99.106:3100/", host: "192.168.99.106"
Sep 09 12:46:03 ubuntu docker[15216]: 2015/09/09 11:46:03 [error] 6#0: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.99.1, server: 192.168.99.106, request: "GET /favicon.ico HTTP/1.1", upstream: "http://192.168.99.106:3100/favicon.ico", host: "192.168.99.106", referrer: "https://192.168.99.106/"
Sep 09 12:46:03 ubuntu docker[15216]: 192.168.99.1 - - [09/Sep/2015:11:46:03 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "https://192.168.99.106/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
```

The log for stf-app@3100.service shows it starting up, and apparantly nothing else:
```
Sep 09 12:10:33 ubuntu systemd[1]: Started STF app.
Sep 09 12:10:34 ubuntu docker[361]: INF/app 1 [*] Using pre-built resources
Sep 09 12:10:34 ubuntu docker[361]: INF/app 1 [*] Listening on port 3000
Sep 09 12:10:34 ubuntu docker[361]: INF/db 1 [*] Connecting to 172.17.9.111:28015
```

Connecting manually to 192.168.99.106:3100 (app address), gives ERR_CONNECTION_REFUSED in a browser. My nginx.conf is identical to the verison in DEPLOYMENT.md, except I changed all the IPs to my local one, 192.168.99.106, where all the services run. Kept the ports the same as the examples in DEPLOYMENT.md:

```
daemon off;
worker_processes 4;

events {
  worker_connections 1024;
}

http {
  upstream stf_app {
    server 192.168.99.106:3100 max_fails=0;
  }

  upstream stf_auth {
    server 192.168.99.106:3200 max_fails=0;
  }

  upstream stf_storage_apk {
    server 192.168.99.106:3300 max_fails=0;
  }

  upstream stf_storage_image {
    server 192.168.99.106:3400 max_fails=0;
  }

  upstream stf_storage {
    server 192.168.99.106:3500 max_fails=0;
  }

  upstream stf_websocket {
    server 192.168.99.106:3600 max_fails=0;
  }

  types {
    application/javascript  js;
    image/gif               gif;
    image/jpeg              jpg;
    text/css                css;
    text/html               html;
  }
        
    map $http_upgrade $connection_upgrade {
    default  upgrade;
    ''       close;
  }

  server {
    listen 80;
    server_name 192.168.99.106;
    return 301 https://$server_name$request_uri;
  }

  server {
    listen 443 ssl;
    server_name 192.168.99.106;
    keepalive_timeout 70;
    root /dev/null;

    # https://mozilla.github.io/server-side-tls/ssl-config-generator/
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/cert.key;
    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:10m;
    ssl_dhparam /etc/nginx/ssl/dhparam.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
    ssl_prefer_server_ciphers on;

    #add_header Strict-Transport-Security max-age=15768000;

    #ssl_stapling on;
    #ssl_stapling_verify on;
    #ssl_trusted_certificate /etc/nginx/ssl/cert.pem;

    resolver 8.8.4.4 8.8.8.8 valid=300s;
    resolver_timeout 10s;

    # Handle stf-provider@cupboard1.service
    location ~ "^/d/cupboard1/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://192.168.99.106:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/mock/ {
      proxy_pass http://stf_auth/auth/mock/;
    }

    location /s/image/ {
      proxy_pass http://stf_storage_image;
    }

    location /s/apk/ {
      proxy_pass http://stf_storage_apk;
    }

    location /s/ {
      client_max_body_size 1024m;
      client_body_buffer_size 128k;
      proxy_pass http://stf_storage;
    }

     location /socket.io/ {
      proxy_pass http://stf_websocket;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }

    location / {
      proxy_pass http://stf_app;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }
  }
}
      
```

**Comment by vbanthia** [comment]
I had the same problem, I fixed it by

Removing 127.0.0.1 from publish port of all the services which starts nodejs server. For example

this will
```
[Unit]
Description=STF app
After=rethinkdb-proxy-28015.service
BindsTo=rethinkdb-proxy-28015.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p-%i
ExecStartPre=-/usr/bin/docker rm %p-%i
ExecStart=/usr/bin/docker run --rm \
  --name %p-%i \
  --link rethinkdb-proxy-28015:rethinkdb \
  -e "SECRET=YOUR_SESSION_SECRET_HERE" \
  -p 127.0.0.1:%i:3000 \
  openstf/stf:latest \
  stf app --port 3000 \
    --auth-url https://stf.example.org/auth/mock/ \
    --websocket-url https://stf.example.org/
ExecStop=-/usr/bin/docker stop -t 10 %p-%i
```

become this

```
[Unit]
Description=STF app
After=rethinkdb-proxy-28015.service
BindsTo=rethinkdb-proxy-28015.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p-%i
ExecStartPre=-/usr/bin/docker rm %p-%i
ExecStart=/usr/bin/docker run --rm \
  --name %p-%i \
  --link rethinkdb-proxy-28015:rethinkdb \
  -e "SECRET=YOUR_SESSION_SECRET_HERE" \
  -p %i:3000 \
  openstf/stf:latest \
  stf app --port 3000 \
    --auth-url https://stf.example.org/auth/mock/ \
    --websocket-url https://stf.example.org/
ExecStop=-/usr/bin/docker stop -t 10 %p-%i
```

You need to do this for all the below services
- stf-app@.service
- stf-auth@.service
- stf-storage-plugin-apk@.service
- stf-storage-plugin-image@.service
- stf-storage-temp@.service
- stf-websocket@.service

After you finish this and restart your units, you will be able to see the login page. But wont be able to login, because there is a small problem in sample nginx.conf file.

You will need to change

```
    location /auth/mock/ {
      proxy_pass http://stf_auth/auth/mock/;
    }
```

to

```
    location /auth/ {
      proxy_pass http://stf_auth/auth/;
    }
```
in your nginx.conf file.

After this, I think you will be ready to enjoy STF in production.

I would like to add one more point here, In my case I am not running nginx using docker, I am running nginx directly on the host server.

**Comment by sorccu** [comment]
Our units have the `127.0.0.1` you removed and they work fine. Nginx runs in a docker container on a separate host, but that shouldn't matter.

**Comment by vbanthia** [comment]
Well truth is I did not research much for the root cause, When I started my units with publish port ```127.0.0.1:... ```. I was able to get valid response from  ``` wget 127.0.0.1:3100 ``` but  ``` wget $IP:3100 ``` was resulting into connection error. 

After removing 127.0.0.1 from publish port, I was getting valid response from ``` wget $IP:3100 ```.

**Comment by MichaelMadsen** [comment]
Removing 127.0.0.1 and changing the nginx.config fixed it. Everything now works, except I can't see the screen of the device - controlling it works, but the field is just blank grey.

**Comment by vbanthia** [comment]
I did a bit research and found that after removing 127.0.0.1, docker will publish or bind it to 0.0.0.0 which means it is binding container port to all the host interface which is not very good or secure. My current best approach will be to bind docker port to IP address itself. eg ``` -p $HOST_STATIC_IP:%i:$PORT```. This will bind only to eth0 interface.

I am still trying to understand why it is working in case of Simo. I can think about two cases.
1. nginx is proxying to localhost instead of raising connection refused.
2. docker container is also binding port to $HOST_IP

@sorccu 
Can you try accessing stf-app server directly using ``` wget $HOST_IP:3100 ```

**Comment by sorccu** [comment]
Ok I went through our units and it looks like I have made a mistake with the example nginx configuration. We are actually using two nginx instances. One of them is on a separate server, and the other is on the same server as the app units with `--net host` enabled, and it's referencing `127.0.0.1` in the config files. That's why it works for us. I'll fix up the documentation later. I think the best option is to remove the 127.0.0.1 for now as you've done.

**Comment by MichaelMadsen** [comment]
I can now take screenshots without problems - my self-signed ssh certificate was ruining the screenshot feature:
```
Sep 09 15:20:00 ubuntu docker[2376]: INF/device:plugins:screen:capture 18 [aa0d987a] Capturing screenshot
Sep 09 15:20:01 ubuntu docker[2376]: ERR/device:support:storage 18 [aa0d987a] Upload to "https://192.168.99.106/s/upload/image" failed Error: certificate has expired
Sep 09 15:20:01 ubuntu docker[2376]: at Error (native)
Sep 09 15:20:01 ubuntu docker[2376]: at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
Sep 09 15:20:01 ubuntu docker[2376]: at TLSSocket.emit (events.js:104:17)
Sep 09 15:20:01 ubuntu docker[2376]: at TLSSocket._finishInit (_tls_wrap.js:460:8)
Sep 09 15:20:01 ubuntu docker[2376]: ERR/device:plugins:screen:capture 18 [aa0d987a] Screen capture failed Error: certificate has expired
Sep 09 15:20:01 ubuntu docker[2376]: at Error (native)
Sep 09 15:20:01 ubuntu docker[2376]: at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
Sep 09 15:20:01 ubuntu docker[2376]: at TLSSocket.emit (events.js:104:17)
Sep 09 15:20:01 ubuntu docker[2376]: at TLSSocket._finishInit (_tls_wrap.js:460:8)
```
Turned off ssh and running on normal http, screenshots work.

Still can't see the feed of the device screen, though. Tested on 4 devices that work in stf -local.
What service is responsible for providing the video feed? Where can I check the logs?

**Comment by vbanthia** [comment]
provider is responsible for fetching device screen. You should check provider unit logs.

**Comment by sorccu** [comment]
I have updated the documentation to remove 127.0.0.1 and added an example rethinkdb.service.

As for the screen not showing up, I think looking at your Chrome developer tools should prove more useful. Go to the network tab, filter by WebSockets and see if something happened with the screen WebSocket.

@MichaelMadsen You can also get rid of the https error by giving the appropriate units `-e NODE_TLS_REJECT_UNAUTHORIZED=0`.

**Comment by vbanthia** [comment]
I have submitted a pull request regarding a problem in sample nginx.conf file, you should also consider this, since most of the people going to use same sample nginx.conf for first time.

https://github.com/openstf/stf/pull/75

**Comment by sorccu** [comment]
Done.

**Comment by MichaelMadsen** [comment]
Yeah, seems like it's not connecting to the websocket.
<img width="1279" alt="screen shot 2015-09-09 at 16 11 03" src="https://cloud.githubusercontent.com/assets/657289/9765744/b0533b84-570d-11e5-88ef-d746664682df.png">

And this is what the only part of the provider log that mentions the websocket:
```
Sep 09 15:53:48 ubuntu docker[1586]: INF/device:plugins:screen:stream 10 [aa0d987a] Starting WebSocket server on port 15000
```

and this is how it's formated in the service file:
```
--screen-ws-url-pattern "wss://192.168.99.106/d/%i/<%= serial %>/<%= publicPort %>/"
```

**Comment by vbanthia** [comment]
I think since you are not using ssl, you should use "ws" URL Scheme for url pattern.

**Comment by MichaelMadsen** [comment]
You're probably right. Changing that one line doesn't seem to be enough, though. Now it just leads to a 404.
<img width="1280" alt="screen shot 2015-09-09 at 16 42 15" src="https://cloud.githubusercontent.com/assets/657289/9766650/ed237f70-5711-11e5-9d8c-cdf527a70d31.png">

I might just try setting ssl up again with the NODE_TLS_REJECT flag instead, in order to stay closer to the example configuration.

**Comment by sorccu** [comment]
Could you show your nginx config?

**Comment by MichaelMadsen** [comment]
Literally just pasted from 443 over to 80 instead, minus the ssl part:

```
daemon off;
worker_processes 4;

events {
  worker_connections 1024;
}

http {
  upstream stf_app {
    server 192.168.99.106:3100 max_fails=0;
  }

  upstream stf_auth {
    server 192.168.99.106:3200 max_fails=0;
  }

  upstream stf_storage_apk {
    server 192.168.99.106:3300 max_fails=0;
  }

  upstream stf_storage_image {
    server 192.168.99.106:3400 max_fails=0;
  }

  upstream stf_storage {
    server 192.168.99.106:3500 max_fails=0;
  }

  upstream stf_websocket {
    server 192.168.99.106:3600 max_fails=0;
  }

  types {
    application/javascript  js;
    image/gif               gif;
    image/jpeg              jpg;
    text/css                css;
    text/html               html;
  }

    map $http_upgrade $connection_upgrade {
    default  upgrade;
    ''       close;
  }

  server {
    listen 80;
    server_name 192.168.99.106;

    keepalive_timeout 70;
    root /dev/null;

    resolver 8.8.4.4 8.8.8.8 valid=300s;
    resolver_timeout 10s;

    # Handle stf-provider@cupboard1.service
    location ~ "^/d/cupboard1/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://192.168.99.106:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
      proxy_pass http://stf_auth/auth/;
    }

    location /s/image/ {
      proxy_pass http://stf_storage_image;
    }

    location /s/apk/ {
      proxy_pass http://stf_storage_apk;
    }

    location /s/ {
      client_max_body_size 1024m;
      client_body_buffer_size 128k;
      proxy_pass http://stf_storage;
    }

    location /socket.io/ {
      proxy_pass http://stf_websocket;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }

    location / {
      proxy_pass http://stf_app;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }

  }

}
```

**Comment by vbanthia** [comment]
your provider name is "cabinet1" while in your nginx config file you have written "cupboard1". 

change ``` location ~ "^/d/cupboard1/([^/]+)/(?<port>[0-9]{5})/$" { ``` -> ``` location ~ "^/d/cabinet1/([^/]+)/(?<port>[0-9]{5})/$" { ```

**Comment by sorccu** [comment]
Nice catch! I didn't spot it either...

Btw I added `NODE_TLS_REJECT_UNAUTHORIZED=0` to the docs as well. Let's try to make them as complete as possible now.

**Comment by MichaelMadsen** [comment]
Well that was a really stupid mistake on my part, well spotted.

Videofeeed and everything else works now, thank you guys for all the help!

**Comment by sorccu** [comment]
Great!

**Comment by marcuccifelicia01** [comment]
marcuccifelicia01@gmail.com

**Comment by rahul0698** [comment]
I am having some problem in running stf-app@.service, stf-migrate.service, stf-reaper.service

status of services..
● stf-websocket@3600.service - STF websocket
Loaded: loaded (/etc/systemd/system/stf-websocket@.service; static; vendor preset: enabled)
Drop-In: /etc/systemd/system/stf-websocket@.service.d
└─override.conf
Active: inactive (dead)

Jul 04 16:01:52 linux-rahul docker[30612]: FTL/db 1 [] No hosts left to try
Jul 04 16:01:52 linux-rahul docker[30612]: FTL/util:lifecycle 1 [] Shutting down due to fatal error
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Main process exited, code=exited, status=1/FAILURE
Jul 04 16:01:52 linux-rahul docker[30766]: Error response from daemon: No such container: stf-websocket-3600
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Control process exited, code=exited status=1
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Unit entered failed state.
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Failed with result 'exit-code'.
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Service hold-off time over, scheduling restart.
Jul 04 16:01:52 linux-rahul systemd[1]: stf-websocket@3600.service: Stop job pending for unit, delaying automatic rest
Jul 04 16:01:52 linux-rahul systemd[1]: Stopped STF websocket.
lines 1-16/16 (END)

● stf-reaper.service - STF reaper
Loaded: loaded (/etc/systemd/system/stf-reaper.service; static; vendor preset: enabled)
Drop-In: /etc/systemd/system/stf-reaper.service.d
└─override.conf
Active: failed (Result: exit-code) since Tue 2017-07-04 16:08:18 IST; 3s ago
Process: 31367 ExecStop=/usr/bin/docker stop -t 10 %p (code=exited, status=0/SUCCESS)
Process: 31348 ExecStop=/usr/bin/docker stop -t 10 %p (code=exited, status=0/SUCCESS)
Process: 31200 ExecStart=/usr/bin/docker run --rm --name %p --link rethinkdb-proxy-28015:rethinkdb openstf/stf:lates
Process: 31192 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
Process: 31183 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)
Process: 31174 ExecStartPre=/usr/bin/docker pull openstf/stf:latest (code=exited, status=0/SUCCESS)
Process: 31166 ExecStartPre=/usr/bin/docker rm %p (code=exited, status=1/FAILURE)
Process: 31158 ExecStartPre=/usr/bin/docker kill %p (code=exited, status=1/FAILURE)
Process: 31151 ExecStartPre=/usr/bin/docker pull openstf/stf:latest (code=exited, status=0/SUCCESS)
Main PID: 31200 (code=exited, status=1/FAILURE)

Jul 04 16:08:17 linux-rahul docker[31200]: INF/db 1 [dev] Unable to connect to 172.17.0.7:28015
Jul 04 16:08:17 linux-rahul docker[31200]: FTL/db 1 [dev] No hosts left to try
Jul 04 16:08:17 linux-rahul docker[31200]: FTL/util:lifecycle 1 [dev] Shutting down due to fatal error
Jul 04 16:08:18 linux-rahul systemd[1]: Stopping STF reaper...
Jul 04 16:08:18 linux-rahul docker[31348]: stf-reaper
Jul 04 16:08:18 linux-rahul docker[31367]: stf-reaper
Jul 04 16:08:18 linux-rahul systemd[1]: stf-reaper.service: Main process exited, code=exited, status=1/FAILURE

● stf-app@3100.service - STF app
Loaded: loaded (/etc/systemd/system/stf-app@.service; static; vendor preset: enabled)
Drop-In: /etc/systemd/system/stf-app@.service.d
└─override.conf
Active: inactive (dead)

Jul 04 15:44:13 linux-rahul docker[29378]: INF/app 1 [] Using pre-built resources
Jul 04 15:44:13 linux-rahul docker[29378]: INF/app 1 [] Listening on port 3000
Jul 04 15:44:13 linux-rahul docker[29378]: INF/db 1 [] Connecting to 172.17.0.7:28015
Jul 04 15:44:14 linux-rahul docker[29378]: INF/db 1 [] Unable to connect to 172.17.0.7:28015
Jul 04 15:44:14 linux-rahul docker[29378]: FTL/db 1 [] No hosts left to try
Jul 04 15:44:14 linux-rahul docker[29378]: FTL/util:lifecycle 1 [] Shutting down due to fatal error
Jul 04 15:44:14 linux-rahul systemd[1]: Stopping STF app...
Jul 04 15:44:14 linux-rahul docker[29536]: stf-app-3100
Jul 04 15:44:14 linux-rahul docker[29552]: stf-app-3100
Jul 04 15:44:14 linux-rahul systemd[1]: Stopped STF app.

my other services that are needed for these service to work are running

CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
6f473dd263b7 openstf/ambassador:latest "/run.sh" 33 minutes ago Up 33 minutes 0.0.0.0:32769->28015/tcp rethinkdb-proxy-28015
162a96d3b7b2 openstf/stf:latest "stf auth-mock --port" 48 minutes ago Up 48 minutes 0.0.0.0:3200->3000/tcp stf-auth-3200
f5f11e62a352 rethinkdb:2.3.5 "rethinkdb --bind all" 2 hours ago Up 2 hours 0.0.0.0:8080->8080/tcp, 0.0.0.0:28015->28015/tcp, 0.0.0.0:29015->29015/tcp rethinkdb
cab4b8344e50 openstf/stf:latest "stf triproxy dev --b" 2 hours ago Up 2 hours stf-triproxy-dev
0bcda7b6a11f openstf/stf:latest "stf triproxy app --b" 2 hours ago Up 2 hours stf-triproxy-app
e62202bbfe23 openstf/stf:latest "stf storage-plugin-i" 2 hours ago Up 2 hours 0.0.0.0:3500->3000/tcp stf-storage-temp-3500
ac9926857cc6 openstf/stf:latest "stf storage-plugin-i" 2 hours ago Up 2 hours 0.0.0.0:3400->3000/tcp stf-storage-plugin-image-3400
1a95bacdeefb openstf/stf:latest "stf storage-plugin-a" 2 hours ago Up 2 hours 0.0.0.0:3300->3000/tcp stf-storage-plugin-apk-3300
d7ac389ce7f6 openstf/stf:latest "stf provider --name " 2 hours ago Up 2 hours stf-provider-floor8
877bde7a6f16 openstf/stf:latest "stf provider --name " 2 hours ago Up 2 hours stf-provider-floor4
1a2441bcf8a9 sorccu/adb:latest "/sbin/tini -- adb -a" 2 hours ago Up 2 hours adbd

I am not able to figure out what is the problem here, please guide. Thanks in advance

**Comment by rahul0698** [comment]
If we are running all services on a single machine rather than running on distributed cluster do we still need rethinkdb-proxy-28015.service. Or we can simply connect other services to rethinkdb.service instead of rethinkdb-proxy-28015. 

Thanks in advance

**Comment by sorccu** [comment]
Not necessarily, it's certainly possible. However we provide no instructions for that.
