### ISSUE TITLE
Clarification of websockets and provider IPs

### ISSUE THREAD

**Issue by MichaelMadsen** [openstf/stf#84]
I'm having some trouble connecting to the device video feed, having moved the provider to a separate VM (remote control works, getting blank video feed and the adb connection string is unable to connect as well). It's definitely because I am configuring wrong, and some clarification of the different IPs would be helpful for me.

So as far as I know, the files that must be configured to add a new provider are stf-provider@.service on the provider machine, and nginx.conf on the webserver.
I have taken the ips of the example configuration files and added in my interpretation/questions.

stf-provider@newprovider.service (running on machine with only adbd.service and a connected android device):
```
[Unit]
Description=STF provider
After=adbd.service
BindsTo=adbd.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p-%i
ExecStartPre=-/usr/bin/docker rm %p-%i
ExecStart=/usr/bin/docker run --rm \
  --name %p-%i \
  --net host \
  openstf/stf:latest \
  stf provider \
    --name "%H/%i" \
    --connect-sub tcp://IP_OF_DEV_TRIPROXY:7250 \
    --connect-push tcp://IP_OF_DEV_TRIPROXY:7270 \
    --storage-url https://IP_OF_STF_STORAGE_TEMP? or maybe    IP_OF_DATABASE?/ \
    --public-ip PUBLIC_IP_OF_THIS_MACHINE \
    --min-port=15000 \
    --max-port=25000 \
    --heartbeat-interval 10000 \
    --screen-ws-url-pattern "wss://IP_OF_WEBSERVER?/d/%i/<%= serial %>/<%= publicPort %>/"
ExecStop=-/usr/bin/docker stop -t 10 %p-%i
```

Nginx.conf:
```
# Handle stf-provider@newprovider.service
    location ~ "^/d/newprovider/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://PUBLIC_IP_OF_PROVIDER:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }
```

So in my case I have 3 machines, 
192.168.99.**106**: app side, running all services and webserver
192.168.99.**107**: rethinkdb, running rethinkdb
192.168.99.**108**: provider, running adbd.service and stf-provider

And I'm a bit unsure where the different IPs would go. At least I haven't hit a combination that works for the video feed yet. And maybe the problem is somewhere else altogether, I'm just pressuming it must be my configuration. Websocket is getting a 504:
<img width="1222" alt="screen shot 2015-09-17 at 15 09 13" src="https://cloud.githubusercontent.com/assets/657289/9935379/300fcc98-5d4e-11e5-8504-594238bf913f.png">

If anybody could point me in the right direction it would be appreciated.

**Comment by sorccu** [comment]
Your assumptions are correct, and `--storage-url` goes to storage-temp. One thing though is that your route is called "newprovider" but in your browser it's "remotehost". However, since you're getting a gateway timeout, I think you actually have them correct in your real configuration. When you get a gateway timeout, it means that nginx was unable to connect to the backend server. So basically if you have `proxy_pass http://PUBLIC_IP_OF_PROVIDER:$port/;`, then your nginx server isn't able to connect to the PUBLIC_IP_OF_PROVIDER. It means that either nothing is running on that port, the port is blocked/firewalled or that your webserver can't access that IP at all.

Two things:

1. Make sure `iptables` on the new provider isn't very restrictive, it needs to have a whole bunch of ports open. Might be worth disabling iptables just to see if that's the issue.
2. I don't think you did this, but just in case: even though the option is called `--public-ip`, it actually means "public within your network" (i.e. an IP all of your users are able to access). While a real public IP might also work, you'd have to do a lot of extra work setting it up and latency would suffer.

**Comment by MichaelMadsen** [comment]
Oh yeah, the newprovider name was just made up for this post, in all of my files it's called remotehost.
```
sudo ufw disable
```
did the trick

I can't believe it was just the default firewall settings, I hadn't even considered it since all remote control and screenshots were working. But I guess that's all handled through the open connection from provider to app side, doesn't mean anything is allowed in.

Thanks for the help.

**Comment by sorccu** [comment]
Great! Note that you can set up a firewall if you want, but you'll need to make sure the range between `--min-port=15000` and `--max-port=25000` is open. You can use a smaller range if you wish.
