### ISSUE TITLE
How many  devices  of one PC connect? what if I want connect more than 28 device to one PC

### ISSUE THREAD

**Issue by daring123** [openstf/stf#961]
I see your read me.
![image](https://user-images.githubusercontent.com/5986074/46572077-a7b7c380-c9b2-11e8-8fea-33d2d7ff4d90.png)

You can connect  28 devices on one PC.However, we want to connect more than 28 devices on one PC.Is there any  solutions to the problem ? If I connect more devices on one PC, what's bad affects ?

**Comment by sorccu** [comment]
It’s just a guideline. You can try more if you want to, but perhaps you’ll run into instability. 28 devices was convenient for us since our PCIE USB card provided 4 ports, and we connected a single 7-port hub to each port. You could, for example, get another PCIE card and double the count. In our experience nesting hubs is not a good idea.
