### ISSUE TITLE
Access device over Wi-Fi

### ISSUE THREAD

**Issue by ahmetkocu** [openstf/stf#97]
Can we add devices that are connected to ADB over tcpip, not connected with USB? When I try this way, cannot see device on sft application.

**Comment by sorccu** [comment]
Yes, but due to ADB USB protocol overhead, it's super slow and unreliable. It's because the protocol sucks and not something we can really fix. When running locally, you can use `stf local --allow-remote`, but then you will not be able to use the demote debugging functionality, as STF would confuse the fake device with a real one and try to set it up, but get confused because the same device is connected twice.
