### ISSUE TITLE
can't see screen on control page

### ISSUE THREAD

**Issue by yz1988computer** [openstf/stf#985]
Hi, I have a question that puzzled me several days

 The phone act when i click or slide on the web side(the phone **can control from the web side**)， but I **cannot see the screen on web side**: 

![image](https://user-images.githubusercontent.com/5734351/48331427-009e0a00-e68b-11e8-87c3-1afab4de620f.png)

When I check **minicap**， the command outputs:

![image](https://user-images.githubusercontent.com/5734351/48331674-d3059080-e68b-11e8-90f5-5556e6dba653.png)

It seems something wrong with JpgEncoder.cpp,  the log paused on "Allocating 7365636 bytes for JPG encoder"( I promise the phone has enough memory):

![image](https://user-images.githubusercontent.com/5734351/48331721-fdefe480-e68b-11e8-9031-619cbff98d40.png)

I find that method on [lib-jpeg repository](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6d8caa9f88184ad1698e91c94b37acb9506dacf0/turbojpeg.c):

![image](https://user-images.githubusercontent.com/5734351/48332328-62ac3e80-e68e-11e8-9317-df4acce1db05.png)

When i use strace ,  outputs:

![image](https://user-images.githubusercontent.com/5734351/48331850-853d5800-e68c-11e8-9990-99334cf13a10.png)

I've no idea how to solve this,  beg for your reply，thanks very much!

**Comment by sorccu** [comment]
Output looks OK.

Please do not remove the issue template. There was a list of questions you were supposed to answer, like what kind of a device you’re trying to use. Issues like this are usually device specific.

**Comment by lileyang2000** [comment]
Hi sorccu,

I work with yz1988computer and I will answer the specific questions with regard to this issue

**What is the issue or idea you have?**
Black screen on the stf control page. 
We have done some debugging work  and it seems minicap process dose not work properly hanging forever (we run the command adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x2248@1080x2248/0 -t  and it fails to output OK ) . After we forced to quit the command , it seems the minicap was stuck in gWaiter.waitForFrame .
![image](https://user-images.githubusercontent.com/17796077/48402088-b473c800-e765-11e8-8639-6767ead85417.png)

**Does it only happen on a specific device? Please run adb devices -l and paste the corresponding row.**
Yes , it only happens on one device.  Since the device is not released yet , it is not available in the open market.  
Here are some details:
The physical size is 1080x2248 
The  density is 480.
The sdk version is 27.
The device supports arm64-v8a eabi.
The device platform is Qualcomm sdm710.

**Please provide the steps to reproduce the issue.**
Just the normal steps and the web side screen is always black as shown in the post by yz1988computer 

**What is the expected behavior?**
The web side screen should show the exact same content as the phone shows.

**Please run stf doctor and paste the output here.**
INF/cli:doctor 24194 [*] OS Arch: x64
2018-11-13T09:39:26.871Z INF/cli:doctor 24194 [*] OS Platform: linux
2018-11-13T09:39:26.871Z INF/cli:doctor 24194 [*] OS Platform: 4.4.0-116-generic
2018-11-13T09:39:26.871Z INF/cli:doctor 24194 [*] Using Node 6.11.4
2018-11-13T09:39:27.001Z ERR/cli:doctor 24194 [*] Unexpected error checking ZeroMQ: Error: libzmq.so.5: cannot open shared object file: No such file or directory
2018-11-13T09:39:27.002Z INF/cli:doctor 24194 [*] Using ADB 1.0.39
2018-11-13T09:39:27.003Z ERR/cli:doctor 24194 [*] RethinkDB is not installed (`rethinkdb` is missing)
2018-11-13T09:39:27.003Z ERR/cli:doctor 24194 [*] ProtoBuf is not installed (`protoc` is missing)
2018-11-13T09:39:27.231Z INF/cli:doctor 24194 [*] Using GraphicsMagick 1.3.23

**Here shows the syslog related to the minicap process. Thank you for your time.** 
Nov  9 23:01:24 ZTE docker[15305]: 2018-11-10T04:01:24.747Z INF/device:plugins:screen:stream 145 [15dd213] **Requesting frame producer to stop**
Nov  9 23:01:24 ZTE docker[15305]: 2018-11-10T04:01:24.748Z INF/device:plugins:screen:stream 145 [15dd213] Disconnecting from minicap service
Nov  9 23:01:24 ZTE docker[15305]: 2018-11-10T04:01:24.750Z INF/device:plugins:screen:stream 145 [15dd213] Stopping minicap service
Nov  9 23:01:24 ZTE docker[15305]: 2018-11-10T04:01:24.750Z INF/device:plugins:screen:stream 145 [15dd213] Sending SIGTERM to minicap
Nov  9 23:01:24 ZTE docker[15305]: 2018-11-10T04:01:24.806Z INF/device:plugins:screen:stream 145 [15dd213] minicap says: "INFO: (jni/minicap/minicap.cpp:197) Received SIGTERM, stopping"

**Comment by habeebshk** [comment]
hey guys have you checked if all the ports are open, I had this issue when the specific port of the device wasn't open in the firewall, you can check this by going into the browser console and see whats blocking it, probably the WebSocket can't open the port
